lib/introspect/assetdeclaration.js, lib/introspect/eventdeclaration.js, lib/introspect/participantdeclaration.js, lib/introspect/transactiondeclaration.js, test/data/model/carlease-nosystem.cto, test/introspect/transactiondeclaration.js, test/models/nosystemmodels.js
Fixes #16 . 
This allows users to add Concerto to their project without specifying a system model. This implies that all base types (Transaction, Event, Asset & Participant) will need to specify an identifying field when a system model is not provided
=> Fix #16 and add unit test

scripts/pkgstamp.js
In travis
N/A
Update script pkgstamp to use `moment-mini`
Not easy to test without merge and test on travis
Only affects deployment scripts
=> (fix) pkgstamp script should use moment-mini as well

lib/introspect/loaders/modelfiledownloader.js, lib/modelmanager.js, package-lock.json, test/modelmanager.js
When a model manager can't find an external model (for example, because of a poorly formed URL). The existing error message is pretty cryptic and doesn't tell the user why the model manager was unable to add the new model file.
Thie PR:
- gives the user more helpful error messages, 
- adds a property to the Error object that gives a helpful error code. The error code can be used by downstream systems to detect when a model download has failed, for example when the system doesn't have a network connection.
- doesn't raise errors at all if the models validate, even if externals models can't be downloaded. For example, if there are local caches versions of the external models, or the external models are unused, the model manager is still useable now.
As exposed through Cicero CLI.
Before
``` …
```
=> feat(modelmanager): Gracefully handle missing external models

lib/introspect/parseexception.js, lib/serializer/validationexception.js, test/introspect/parseexception.js
The fix allows a user to override the default `fullMessage` in a parse error.
It also removes redundant `fileName` in `fileLocation` for `ParseException` since those are now by default in the `BaseFileException`.
1.
2.
3.
4.
=> feature(errors) Allow overriding of the full message in a parse error

lib/introspect/illegalmodelexception.js, lib/modelmanager.js, package-lock.json, test/introspect/illegalmodelexception.js, test/introspect/semantic_validation.js
Exception returned by the API should not carry the whole model if possible. This removes the `modelFile` field from `IllegalModelExceptions`. `fileName` is used to retrieve the model file when needed instead.
1.
2.
3.
4.
All tests are passing as before. At least one test uses access to the model file from their name when an illegal model error occurs.
=> errors(models) remove modelfile from IllegalModelException

api.txt, changelog.txt, lib/introspect/assetdeclaration.js, lib/introspect/classdeclaration.js, lib/introspect/conceptdeclaration.js, lib/introspect/enumdeclaration.js, lib/introspect/enumvaluedeclaration.js, lib/introspect/eventdeclaration.js, lib/introspect/field.js, lib/introspect/modelfile.js, lib/introspect/participantdeclaration.js, lib/introspect/property.js, lib/introspect/relationshipdeclaration.js, lib/introspect/transactiondeclaration.js, lib/modelmanager.js, package.json, test/introspect/assetdeclaration.js, test/introspect/enumdeclaration.js, test/introspect/property.js, test/modelmanager.js
Resolves #47 
Adds custom `instanceof` implementation through the use of [`Symbol.hasInstance`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance) to allow comparison of different module instances.
=> fix(47): Adds custom instanceof implementation to allow comparison of different module instances

MAINTAINERS.md
Remove Caroline Church and Simon Stone from the maintainers list.
=> (chore) update maintainer list

packages/concerto-cli/index.js, packages/concerto-cli/package.json, packages/concerto-core/lib/modelmanager.js
Basic functionality in Concerto CLI.
Usage:
```
concerto get --ctoFiles model.cto [--out ./models]
```
- Fixes CLI dependencies, and bug in `modelManager.writeModelsToFileSystem`
=> fix(cli): CLI now functional

package.json, packages/concerto-cli/index.js, packages/concerto-tools/package.json
CLI help uses the concerto name.
=> fix(CLI) use concerto name

README.md
Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Adding the license badge and slack badge in README.
- Adding the Slack Badge in README
- Adding the License Badge in README
- None
- https://github.com/accordproject/techdocs/issues/78
- https://github.com/accordproject/techdocs/issues/82
=> docs(README): adds slack badge, adds license badge

package-lock.json, packages/concerto-cli/index.js, packages/concerto-cli/test/models/parseerror.cto, packages/concerto-cli/test/models/typenotfound.cto, packages/concerto-core/index.js, packages/concerto-core/lib/codegen/fromjs/plantumlgenerator.js, packages/concerto-core/lib/codegen/parsejs.js, packages/concerto-core/lib/logger.js, packages/concerto-core/lib/tools/changelog.js, packages/concerto-core/lib/tools/plantumltoimage.js, packages/concerto-core/lib/tools/versionchecker.js, packages/concerto-core/package.json, packages/concerto-core/scripts/api-changelog.js, packages/concerto-core/test/logger.js, packages/concerto-core/test/models/animaltracking.js
- Move logger from `markdown-transform` to `concerto-core`
- Use logger for console and errors
- Remove duplicate message from errors in CLI
=> feature(logger) Proper logger support and error reporting in CLI

packages/concerto-core/lib/tools/versionchecker.js
Updated versionchecker.js to include a reminder to update TypeScript definitions.
1. Fixed minor punctuation error in versionchecker.js.
2. Added a reminder to update TypeScript definitions when hash comparison indicates the user has updated the API.
=> #82: Automated API Verification now reminds users to update TypeScript definitions

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/serializer.js, packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/test/models/wildcards.js, packages/concerto-core/test/serializer/jsongenerator.js, packages/concerto-core/test/serializer/jsonpopulator.js
Supports `ergo` option on the serializer.
=> feature(validation) add Ergo-style validation

packages/concerto-cli/README.md, packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-cli/test/models/org.hyperledger.composer.system.cto
- Add `--ctoSystem` option to CLI
- Default system is base Accord Project one
- Refactor so system and user models are loaded consistently from disk or URL in the various commands
- Add info output when `cicero get` succeeds
Examples:
```
bash-3.2$ ./index.js get --ctoFiles https://models.accordproject.org/docusign/connect@0.2.0.cto --outputDirectory dsout 
./index.js get --ctoFiles https://models.accordproject.org/docusign/connect@0.2.0.cto --outputDirectory dsout 
13:26:55 - info: Loaded external models in 'dsout'.
bash-3.2$ ./index.js get --ctoSystem ./test/models/org.hyperledger.composer.system.cto --ctoFiles https://models.accordproject.org/docusign/connect@0.2.0.cto --outputDirectory dsout 
./index.js get --ctoSystem ./test/models/org.hyperledger.composer.system.cto --ctoFiles …
```
=> Fix for issue #89: Add ctoSystem option to CLI, other CLI improvements

README.md
Signed-off-by: Parikshit Hooda <phooda804@live.com>
fixed typos in the readme markdown.
- changed the word 'optionall' to 'optionally' as discussed in #107 . changed 'an' to 'a' in a couple places to comply with English grammar rules.
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
=> refactor(README): change README - issue#106

CONTRIBUTING.md
Signed-off-by: Arshad Kazmi <arshadkazmi42@gmail.com>
This PR fixes the broken link of code of conduct in CONTRIBUTING.md file
- Change the old code of conduct url (`https://github.com/accordproject/docs/blob/master/Accord%20Project%20Code%20of%20Conduct.pdf`) to new url (`https://lfprojects.org/policies/code-of-conduct/`)
=> fix(CONTRIBUTING): broken coc link - I123

CONTRIBUTING.md, DEVELOPERS.md, ISSUE_TEMPLATE.md, README.md
Signed-off-by: Michael Zhou <myz227@nyu.edu>
<OVERALL SUMMARY OF PULL REQUEST>
Updated documentation to be consistent with other AP repos by correcting improper markdown links and ensuring consistency in markdown style. Also fixes typos, grammar, and punctuation errors in documentation. All tests confirmed to pass.
- Modified markdown to be more appropriate with content of associated links
- Tailored certain links to refer to the contents of this repo specifically
- Fixed typos and miscellaneous errors in punctuation and grammar
- Ensured README structure and layout is consistent with those of other AP repos
- [Cicero Template Library Issue 257](https://github.com/accordproject/cicero-template-library/issues/257)
- Pull Request [#280](https://github.com/accordproject/cicero-template-librar …
=> docs(*): update documentation and fix typos - I65

packages/concerto-cli/index.js
Fixes `argv` field for the `target` option in the `compile` command.
=> fix(CLI) compile use new 'target' option rather than 'format'

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-cli/test/data/model.cto, packages/concerto-cli/test/data/sample.json
- Ensure the `--ctoFiles` parameters are being passed
- Provide for a default sample and corresponding error message in `validate`
=> fix(CLI) Some better error messages for missing file and arguments

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/factory.js, packages/concerto-core/lib/serializer.js
This is a leftover fix for #47. Although it was closed, some of the tests in Accord Project Cicero use instance of on either `Factory` or `Serializer`. This should provide for a more reliable way to test those.
=> fix(core) Add instanceof alternatives for Serializer and Factory objects

packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/test/serializer.js, packages/concerto-core/test/serializer/jsongenerator.js, packages/concerto-core/test/serializer/jsonpopulator.js, packages/concerto-core/test/serializer/resourcevalidator.js
A stricter validation/serialization semantics for atomic types and values in CTO models.
- #157 Atomic values in the JSON have to be strictly of the type declared in the model. E.g., `true` validates against `Boolean` but `"true"` does not. E.g., `3.14` validates against `Double` but does not validate against `Integer` or `Long`. E.g., `"1"` validates against `String` but `1` does not.
- #158 Serializing non-finite Doubles (`NaN` or `Infinity` or `-Infinity`) throws a validation error
- Updates the tests accordingly
- This is a breaking change
- The PR is against a new `release-0.83` branch
=> feature(core) Stricter validation for atomic values

packages/concerto-core/lib/config/configmediator.js
Hide this constant from jsdocs generation by fixing a type in the `@private` jsdoc annotation
=> docs(configmediator): Fix typo in JSDoc

README.md, packages/concerto-core/lib/logger.js
Signed-off-by: Nikolay Vlasov <vlason@amazon.com>
Introduced a new environment variable called `CONCERTO_LOG_FOLDER_PATH` to set a custom log path for concerto.
- Added a new environment variables and the way the logs directory path is set in `concerto-core/lib/logger.js`
- Updated the readme with a note on how to set the variable.
- This modification is needed to make concerto compatible with Amazon Lambda function on AWS cloud.
- Issue #183
=> feature(core): Setting custom logs folder with environment variable

packages/concerto-core/lib/serializer/instancegenerator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/lib/serializer/valuegenerator.js, packages/concerto-core/package.json, packages/concerto-core/test/serializer/instancegenerator.js, packages/concerto-core/test/serializer/valuegenerator.js
Adds functions that generate valid range and regex values when generating sample and empty instance JSON values.
=> feat(valuegenerator): Generate valid values for Regex and Range meta properties

packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, packages/concerto-tools/test/codegen/fromcto/jsonschema/jsonschemavisitor.js
Fix an issue in the new JSON Schema generation where the definitions get overwritten by the last model file processed.
=> fix(json-schema) : handle multiple model files

package-lock.json, package.json, packages/concerto-cli/package.json, packages/concerto-core/lib/factory.js, packages/concerto-core/lib/model/typed.js, packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/lib/serializer/objectvalidator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/lib/serializer/valuegenerator.js, packages/concerto-core/package.json, packages/concerto-core/test/composer/i18n.js, packages/concerto-core/test/factory.js, packages/concerto-core/test/model/resource.js, packages/concerto-core/test/model/typed.js, packages/concerto-core/test/models/model.js, packages/concerto-core/test/models/test.js, packages/concerto-core/test/serializer/complex/complex.js, packages/concerto-core/test/serializer/instancegenerator.js, packages/concerto-core/test/serializer/jsongenerator.js, packages/concerto-core/test/serializer/jsonpopulator.js, packages/concerto-core/test/serializer/objectvalidator.js, packages/concerto-core/test/serializer/resourcevalidator.js, packages/concerto-tools/package.json, scripts/pkgstamp.js
Signed-off-by: Diana Lease <dianarlease@gmail.com>
-  Migrates concerto to use dayjs instead of moment due to the reasons described in #205 
- We no longer preserve the timezone offset as we did with `Moment.parseZone()` bc dayjs does not offer equivalent functionality.
- Dayjs is less strict about what it will parse as a date. To combat this, this PR adds validation to check if the value is undefined or not a string in `serializer/objectvalidator.js`
- I'll keep this PR open to discuss on next weeks's WG call
=> chore(datetime): migrate from moment to dayjs

.github/workflows/build.yml
- Bug fix: micro-publish to npm should be tagged with `unstable`
- "latest" is also fixed in npm, pointing correctly again to `8.11`
https://www.npmjs.com/package/@accordproject/concerto-cli
https://www.npmjs.com/package/@accordproject/concerto-core
https://www.npmjs.com/package/@accordproject/concerto-tools
=> fix(publish) Micro-publish to npm should be tagged unstable

.github/workflows/publish.yml
- Uses correct `NPM_TOKEN` in publish workflow
=> fix(publish) Use correct NPM token

.github/workflows/build.yml, .github/workflows/publish.yml, scripts/timestamp.js
- Add script to detect whether publishing a stable or prerelease version
- Turn signoff on in in version PR (for DCO)
=> chore(build) detect prereleases in publish workflow

.github/workflows/publish.yml
- Turn on publication to npm for releases
- Test seems conclusive in #223
=> chore(build) Turn on publish workflow

package-lock.json, packages/concerto-core/lib/modelmanager.js, packages/concerto-core/test/modelmanager.js
Adds abstract types to the system `concerto` namespace:
```
namespace concerto
abstract concept Concept {}
abstract asset Asset {}
abstract transaction Transaction {}
abstract participant Participant {}
abstract event Event {}
```
=> feat (root types) : add abstract root types in concerto ns

.github/workflows/build.yml, .github/workflows/publish.yml, packages/concerto-core/test/introspect/loaders/jobqueue.js
We need to do a second round of design on CI migration from Travis to GitHub Actions because:
1. we have to variants now with slightly different takes in https://github.com/accordproject/concerto/tree/master/.github/workflows and https://github.com/accordproject/cicero/tree/master/.github/workflows
2. We need to decide which node version we support
3. Better to maintain one well understood version to make our lives easier
4. Travis is being _very_ capricious and the matter feels more urgent than it was a year ago
- Consolidate GitHub action workflows for build/testing/publication to npm
- Still draft, one key question is when is `lerna` installed and how, but want this PR ready for discussion on Tech WG call
=> chore(CI) Align github workflows with cicero

package-lock.json, package.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/serializer.js, packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/package.json
Allows to specify an `utcOffset` parameter used to construct Dayjs object during validation.
- Additional option `utcOffset` is added to the Concerto validation code.
- Upgrade to latest `dayjs` library
=> feature(validator) Add optional UTC offset parameter to validation

package.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/introspect/parser.js, packages/concerto-core/lib/introspect/parser.pegjs, packages/concerto-core/test/data/model/versionInvalid.cto, packages/concerto-core/test/data/model/versionValid.cto, packages/concerto-core/test/introspect/concertoVersion.js
Adds optional pragma to concerto model files, allowing a user to declare a Concerto version range for that model.
- Adds optional `concerto version "<SEMVER RANGE>"` to concerto model files.
- Adds `ModelFile.getConcertoVersion` API call to inspect the version range on models.
- Issue #255
=> feature(cto) Add concerto version pragma

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/factory.js, packages/concerto-core/test/factory.js
Remove unused and inconsistent `allowEmptyId` option on factory API.
- Remove `allowEmptyId` option
=> fix(core) Remove  option on factory API

scripts/tag.js
- To properly publish new releases, we need to use the `latest` tag rather than simply `stable`
=> fix(build) use 'latest' tag rather than 'stable' for publication

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js
Fixes options handling for CLI validation with `--ergo` option.
- Passes ergo option only on `toJSON` output during validation
=> fix(cli) Passes proper options for Ergo validation

packages/concerto-core/types/index.d.ts
- Small adjustment to typescript API: `ModelManager.getType()` is useful to have publicly available
=> fix(ts) Make ModelManager.getType call public in TypeScript

packages/concerto-core/lib/introspect/parser.js, packages/concerto-core/lib/introspect/parser.pegjs, packages/concerto-core/lib/introspect/stringvalidator.js, packages/concerto-core/test/introspect/field.js, packages/concerto-core/test/introspect/stringvalidator.js
- Handles regular expressions with flags
- Parser already supported them, but now string validation
- With this fix, we can properly handle complex regular expressions with unicode as needed to validate names in the metamodel (#298)
=> fix(core) Properly handles flags in string regex validators

packages/concerto-tools/lib/codegen/fromJsonSchema/cto/inferModel.js, packages/concerto-tools/schema.json, packages/concerto-tools/test/codegen/fromJsonSchema/cto/data/2020-schema.json, packages/concerto-tools/test/codegen/fromJsonSchema/cto/data/modifiers-schema.json, packages/concerto-tools/test/codegen/fromJsonSchema/cto/inferModel.js
- Adds support for 2019 draft, draft-06 and draft-07 of JSON Schema.
- Adds detection and support for 2020-12 draft of JSON Schema (this is not backwards compatible with previous drafts).
- Adds support for `pattern`, `minimum` and `exclusiveMaximum` modifiers.
- Adds support for recursive definitions in JSON Schema.
- Adds support for `$defs` in addition to `definitions`
- Adds inference for namespace and root type name from the `$id` property
I feel that this is starting to stablise and could be considered for inclusion in the public API and CLI.
=> feat(codegen): Improve JSON Schema to Concerto inference

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-core/test/introspect/metamodel.js
- Add test for importing / exporting metamodel itself (good check for complex models with regex, decorators support etc.)
- Add `--output <file>` option to `import` and `export` commands in the CLI
=> Chore: Metamodel Testing and CLI import/export options

packages/concerto-core/package.json
- `semver` moved from `devDependencies` to `dependencies` in `@accordproject/concerto-core`
Tested with the micro-publish:
```
zsh-5.8$ npm install -g @accordproject/concerto-cli@1.1.1-20210811120929 
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/Users/jerome.simeon/.nvm/versions/node/v14.16.1/bin/concerto -> /Users/jerome.simeon/.nvm/versions/node/v14.16.1/lib/node_modules/@accordproject/concerto-cli/index.js
+ @accordproject/concerto-cli@1.1.1-20210811120929
added 3 packages from 2 contributors and updated 3 packages in 6.512s
zsh-5.8$ concerto -help
concerto <cmd> …
```
=> fix(dep) semver is a dependency for concerto-core

package-lock.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/factory.js, packages/concerto-core/package.json, packages/concerto-core/test/1.0.0/validate.js, packages/concerto-core/types/index.d.ts
Currently installing the `concerto-core` module results in the following warning:
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
This is because it depends on `uuid@3.4.0`. This change moves to `uuid@8.3.2`.
Unfortunately the way the `uuid` module is written means that it is no longer possible to stub. To get the affected tests working again, I have added a new `Factory.newId` function that can be stubbed instead.
=> chore(deps): move to uuid@8

packages/concerto-tools/types/index.d.ts
Fix issue #318 by wrapping all of the code generating classes in a `CodeGen` namespace to reflect the actual exports structure of the `concerto-tools` module.
=> fix(typescript): wrap codegen types in namespace

packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/test/data/model/versionValid.cto, packages/concerto-core/test/introspect/concertoVersion.js
Update model file parsing to enable the specified Concerto version range (for example, `concerto version "^1.0.0"`) to match a pre-release version of Concerto (for example, `1.1.3-20210826140311`). This fixes the pain point in issue #326 by making it possible to install `@accordproject/concerto-core@unstable` and use it without changing your model files to match.
=> feat(models): allow prerelease concerto versions to match (resolves #326)

packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-tools/lib/codegen/codegen.js, packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
Adds a new visitor to convert CTO to a set of classes and namespaces
- Adds a CSharpVisitor
- Adds unit tests
- Does not use [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types) available in C# 8.0
- No special handling for `$identifier` fields
=> feat(codegen) : convert cto to csharp

package-lock.json, packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js, packages/concerto-tools/output/test.MyRequest.json, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js
- Generate Typescript interfaces
- Export abstract types in JSON Schema
=> fix: generate interfaces for typescript. JSON schema should include abstract types.  #345 and #346

packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/modelmanager.js, packages/concerto-core/lib/modelutil.js, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/test/models/test.js, packages/concerto-core/test/modelutil.js
This PR cleans up import handling which can be made simpler with the new parser using the Concerto Metamodel. Notably:
- Builds simpler import tables for wildcard and non-wildcard
- Avoid using fully qualified names which have to be parsed again when possible
- Also cleans up what looks like obsolete code in `ModelUtil`
=> refactor(imports) clean up import handling from parser

CONTRIBUTING.md, README.md
Updated the Accord Project community link in the docs from the old & inactive Slack link to the new Discord server link
=> docs(README & CONTRIBUTING): updated slack link to discord's - #369

CONTRIBUTING.md, packages/concerto-core/index.js, packages/concerto-cto/index.js, packages/concerto-util/index.js, packages/concerto-vocabulary/index.js
- Changes typographic error
- Issue #372
=> Minor Typo

packages/concerto-core/lib/introspect/numbervalidator.js, packages/concerto-core/test/introspect/numbervalidator.js
Signed-off-by: Jerome Simeon <Jerome.Simeon@docusign.com>
- Improves error messages for out of range numeric values
=> fix(core) Better error messages for out of range numeric values

packages/concerto-util/index.js, packages/concerto-util/lib/label.js, packages/concerto-util/lib/modelwriter.js, packages/concerto-util/test/label.js
Signed-off-by: Jerome Simeon <Jerome.Simeon@docusign.com>
- New `Label` utilities to convert Concerto identifiers to sentences and back
- Replaces and extends proposed PR in #378
=> feature(util): Add label utility functions

packages/concerto-core/changelog.txt, packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/test/data/model/versionValid.cto, packages/concerto-core/test/introspect/concertoVersion.js
- This fixes a regression in Concerto `2.0.0-alpha.1` where `ModelManager.updateExternalModels` no longer returned the set of external models as model files.
- Also fixes tests for concerto versions so they pass for the new release
=> fix(core): Regression in update external models not returning model files

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js, packages/concerto-tools/lib/codegen/fromcto/graphql/graphqlvisitor.js, packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js, packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js, packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js, packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js, packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js, packages/concerto-tools/types/lib/codegen/fromcto/csharp/csharpvisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/golang/golangvisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/graphql/graphqlvisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/java/javavisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/jsonschema/jsonschemavisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/plantuml/plantumlvisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/typescript/typescriptvisitor.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/xmlschema/xmlschemavisitor.d.ts
The visitor `visit` methods should be public, as these can be called from outside of the class.
=> fix(types): visitor visit methods should be public

README.md, contrib-notes/coding-guidelines.md
Updates some stale links to Slack to now point to Discord
=> docs(readme): update links to discord

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/concerto.js, packages/concerto-core/types/lib/concerto.d.ts
The Concerto class currently uses`{*}` as the type for `getModelManager`, which results in `any` being generated for the TypeScript types. This change corrects the code to reference the `ModelManager` class instead. 
=> fix(types): correct model manager type for concerto method

packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js, packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js
- Uses the `import type` syntax to ensure that circular imports are erased during build of TypeScript files that are generated by `concerto-tools` code generation. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html
=> feat(tools): typescript codegen, protect against circular dependencies

.github/workflows/build.yml, packages/concerto-types/package.json
The package publishing workflow only does a `npm ci` at the moment, and not a `npm run build` like the other workflows - this change uses the same combination of steps everywhere.
Also, the package versions in the new `concerto-types` package are wrong - this change updates them to 2.2.1.
=> fix(*): correct versions and workflow

packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js, packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js, packages/concerto-tools/types/lib/codegen/fromcto/typescript/typescriptvisitor.d.ts
Adds support for the literal and union decorators to the typescript generator so that it correctly handles literal and union generation.
- Adds support for the union decorator to the typescript generator
- Adds support for the literal decorator to the typescript generator
N/A?
N/A?
- Issue #429
- Pull Request #431
=> feat(types): Adding union and literal decorators to the typescript generation

packages/concerto-core/changelog.txt, packages/concerto-core/lib/introspect/metamodel.js
The return types for `newMetaModelManager` and `modelManagerFromMetaModel` are currently `*` or `object`, neither of which are helpful to TypeScript developers. This change corrects the return types to `ModelManager`.
=> fix(*): correct metamodel function return types

packages/concerto-core/lib/introspect/modelfile.js
Fix a bad error message which occurs when calling `getFullyQualifiedTypeName()` when the type of the property relies on an imported namespace that is not present in the model manager.
Error before this change:
`11:19:28 - ERROR: Cannot read properties of undefined (reading 'getLocalType')`
Error after this change:
`11:21:07 - ERROR: Failed to find fully qualified type name for property common with type Common`
=> fix(*): wrong error getting fully qualified type name

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/types/lib/codegen/fromcto/csharp/csharpvisitor.d.ts
Extends the C# code generation to:
1. optionally support NewtonsoftJson as a serialization / deserialization library
2. add `useNewtonsoftJson` and `useSystemTextJson` as flags to the `concerto compile` CLI.
3. prefix C# namespaces with `Concerto.Models` to avoid clashes with other packages.
4. make `enum` declarations public
5. switch from `new` modifier to use `virtual`/`override` modifiers for classes. See https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords
6. make Enum fields nullable to prevent C# from making an assumption about a default value
7. escape field names that are reserved keywords in C#
- This change is used by the new `concerto-dotnet` library, https://github.com/accordproject/concerto-dotnet
=> feat(tools): improved C# code generation

packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-cli/test/models/version-a.cto, packages/concerto-cli/test/models/version-b.cto, packages/concerto-cli/test/models/version-c.cto
- Improve `concerto version` command so that it updates the version numbers in any affected `import` statements across the specified set of model files
- CTO model file updating is messy as roundtripping a CTO model through the parser is lossy (whitespace, comments)
```
% concerto version patch --models ?.cto
09:34:27 - INFO: Updated version of "/Users/Simon.Stone/git/models-registry/features/fixtures/a.cto" from "3.4.5" to "3.4.6"
09:34:27 - INFO: Updated version of "/Users/Simon.Stone/git/models-registry/features/fixtures/b.cto" from "2.3.4" to "2.3.5"
09:34:27 - INFO: Updated version of "/Users/Simon.Stone/git/models-registry/features/fixtures/c.cto" from "1.2.3" to "1.2.4"
```
```
--- a/features/fixtures/a.cto
+++ b/features/fixtures/a.cto
@@ -1,6 +1,6 @@
-namespace …
```
=> feat(cli): extend concerto version to update imports (resolves #465)

packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/modelutil.js, packages/concerto-core/types/lib/introspect/modelfile.d.ts, packages/concerto-core/types/lib/modelutil.d.ts
- Expose certain `ModelUtil` methods and correct the TypeScript types for `parseNamespace`
- Remove a seemingly redundant codepath from `ModelFile.getFullyQualifiedTypeName`
=> fix(*): expose model util methods, remove redundant type lookup

package-lock.json, packages/concerto-cli/lib/commands.js, packages/concerto-cli/package.json, packages/concerto-tools/package.json, packages/concerto-util/lib/filewriter.js, packages/concerto-util/package.json, packages/concerto-util/test/filewriter.js
Removes the usage of the `mkdirp` module to recursively create directories, replacing it with `fs.mkdirSync(path, {recursive:true})`
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> (chore) remove mkdirp dep

package-lock.json, packages/concerto-core/package.json, packages/concerto-cto/package.json, packages/concerto-tools/package.json, packages/concerto-util/package.json
The Concerto modules cannot currently be used in a Node.js application:
```
{"$class":"concerto.metamodel@1.0.0.TypeIdentifier","name":"Model"},"isArray":true,"isOptional":false}]}]}')}},t={},function r(n){var o=t[n];if(void 0!==o)return o.exports;var u=t[n]={exports:{}};return e[n](u,u.exports,r),u.exports}(10);var e,t}));
^
ReferenceError: self is not defined
at Object.<anonymous> (/home/jenkins/workspace/models-registry_PR-111/node_modules/@accordproject/concerto-cto/dist/concerto-cto.js:2:212)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require …
```
=> fix(*): use webpack version for browsers

packages/concerto-analysis/src/compare-config.ts, packages/concerto-analysis/src/compare-utils.ts, packages/concerto-analysis/src/comparers/properties.ts, packages/concerto-analysis/test/fixtures/identical.cto, packages/concerto-analysis/test/fixtures/number-validator-added.cto, packages/concerto-analysis/test/fixtures/number-validator-changed-lowercompat.cto, packages/concerto-analysis/test/fixtures/number-validator-changed-lowerincompat.cto, packages/concerto-analysis/test/fixtures/number-validator-changed-uppercompat.cto, packages/concerto-analysis/test/fixtures/number-validator-changed-upperincompat.cto, packages/concerto-analysis/test/fixtures/string-validator-added.cto, packages/concerto-analysis/test/fixtures/string-validator-changed.cto, packages/concerto-analysis/test/fixtures/validators.cto, packages/concerto-analysis/test/unit/compare.test.ts, packages/concerto-core/index.js, packages/concerto-core/lib/introspect/field.js, packages/concerto-core/lib/introspect/numbervalidator.js, packages/concerto-core/lib/introspect/stringvalidator.js, packages/concerto-core/lib/introspect/validator.js, packages/concerto-core/test/introspect/numbervalidator.js, packages/concerto-core/test/introspect/stringvalidator.js, packages/concerto-core/test/introspect/validator.js, packages/concerto-core/types/index.d.ts, packages/concerto-core/types/lib/introspect/field.d.ts, packages/concerto-core/types/lib/introspect/validator.d.ts
Extend `concerto compare` so that it can compare number and string validators attached to a field.
This will catch:
- Number validator added to a field (incompatible change)
- Lower bound of a number validator increased (incompatible change)
- Lower bound of a number validator decreased (compatible change)
- Upper bound of a number validator decreased (incompatible change)
- Upper bound of a number validator increased (compatible change)
- String validator added to a field (incompatible change)
- String validator regex pattern changed (incompatible change)
- String validator regex flags changed (incompatible change)
Note that for regexes, it may be possible to make a regex more lenient than it was before, but there is no way for us to programmatically assert that one regex is more lenient …
=> feat(*): extend concerto compare to include field validators

packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/test/serializer/jsonpopulator.js, packages/concerto-core/types/lib/serializer/jsonpopulator.d.ts
This change removes the data values from error messages when model validation fails.  Instead, error messages now report the path in the object being validated where the error occurs. A client application could choose to parse the JSONPath expression to find the offending value.
```
ERROR: Expected value "2022-08-04T10:07asda" to be of type DateTime
```
```
ERROR: Expected value at path `$.identityVerification.date` to be of type `DateTime`
```
I also add a test that demonstrates the more advanced error output, previously we had full coverage, but the tests only demonstrated base cases. Surprisingly few tests failed due to this change!
=> chore(jsonpopulator): remove data values from validation error messages

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js
In CI/CD pipelines, it may be desirable to set just the prerelease identifier for a model file before publishing. For example, in a pull request, I may want to set the prerelease identifier for a model published as part of a pull request with version `1.2.3` to `1.2.3-pr.1234567`. This is easy to do if you know the version of the model, but harder where you want to set the same prerelease identifier for a set of models with different versions.
This change updates the `concerto version` command to allow `concerto version keep --prerelease pr.1234567` to only set the prerelease identifier for all specified models, and preserve the existing version.
=> feat(*): add keep and set prerelease option to version command

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js
Extend the `concerto compile` command with an additional `--metamodel` option that users can specify to include the metamodel in the compiled output. This option can be specified with other models, or without (if you just want the metamodel).
=> feat(*): add compile option for including metamodel

package-lock.json, packages/concerto-analysis/src/compare.ts, packages/concerto-analysis/test/unit/compare.test.ts, packages/concerto-cli/lib/commands.js, packages/concerto-cli/package-lock.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/modelloader.js, packages/concerto-core/lib/modelmanager.js, packages/concerto-core/package-lock.json, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/test/semver.js, packages/concerto-core/types/lib/basemodelmanager.d.ts, packages/concerto-core/types/lib/introspect/modelfile.d.ts, packages/concerto-core/types/lib/modelloader.d.ts, packages/concerto-core/types/lib/modelmanager.d.ts, packages/concerto-types/scripts/codegen.js
This change is an incremental step towards dropping support for Wildcard Imports. This change prevents their use in "strict" mode, and warns in the default mode.
- Renames `isVersionedNamespacesStrict` to `isStrict` in ModelManager
- Adds a warning when a `concerto.metamodel@1.0.0.ImportAll` is encountered in a `ModelFile`.
- Throws an error when a `concerto.metamodel@1.0.0.ImportAll` is encountered in a `ModelFile` when in strict mode.
- Required for 3.0 release, Issue #420
=> BREAKING CHANGE(core): rename strict option, ban wildcard imports in strict mode

package-lock.json, packages/concerto-core/lib/rootmodel.js, packages/concerto-core/lib/rootmodel.json, packages/concerto-metamodel/lib/metamodel.json, packages/concerto-metamodel/lib/metamodelutil.js, packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
This change allows the .NET namespace for generated C# classes to be specified via a decorator in the model:
```
@DotNetNamespace("Org.Acme.Models")
namespace org.acme
```
This allows the model author to shape the generated output in a way similar to Protocol Buffers: https://github.com/hyperledger/fabric-protos/blob/main/gateway/gateway.proto#L7
I've also updated the metamodel to use this decorator to generate the Concerto types in the `AccordProject.Concerto` namespace to match our package in https://github.com/accordproject/concerto-dotnet
=> feat(*): allow c# namespace to be specified via decorator

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/types/lib/codegen/fromcto/csharp/csharpvisitor.d.ts
When compiling the `concerto@1.0.0` model to C#, the `virtual` modifier is not used on the `$class` property because we only do this if the namespace is `concerto`. This fixes the code to parse the namespace and ignore the version component.
=> fix(*):  property wrong for versioned concerto base class

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js
Add a `--strict` option to `concerto compile` which mandates versioned namespaces and imports and stops it producing both `concerto` and `concerto@1.0.0` code.
=> feat(*): enable strict mode for cli in compile

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
The .NET package for Concerto now has a `Type` attribute that can be used to associate model information with a .NET class, and make it possible to find all of the available .NET classes generated by Concerto (find all classes in all assemblies with the attribute).
This change adds this attribute to the generated C# code as follows:
```
[AccordProject.Concerto.Type(Namespace = "concerto", Version = "1.0.0", Name = "Concept")]
public abstract class Concept {
[JsonPropertyName("$class")]
public virtual string _class { get; } = "concerto@1.0.0.Concept";
}
```
=> feat(*): add type attributes to generated c#

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
This change:
- Removes all of the `using` statements for `System`, `Newtonsoft`, etc and instead fully qualifies any type references; this removes warnings about unused `using` statements for things like `System` when you have no `DateTime` properties.
- Sets the correct JSON converter on all concepts using the classes from the new `AccordProject.Concerto` package.
- Sets the correct JSON converter on all enums using the built-in "string enum value" converters.
=> feat(*): align with concerto-dotnet changes

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js
Adds a new command to the Concerto command line tool to generate a sample JSON instance of a type.
```console
$ concerto generate sample --model person.cto --concept org.accordproject.person.Person --includeOptionalFields
{
"$class": "org.accordproject.person.Person",
"identifier": "resource1",
"additionalName": "Duis in ut ad elit.",
"address": {
"$class": "org.accordproject.address.PostalAddress",
"streetAddress": "Officia.",
"postalCode": "Reprehenderit aliqua pariatur.",
[...]
}
```
=> feat(cli): add generate command for cli

package-lock.json, packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/package.json, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/types/lib/codegen/fromcto/csharp/csharpvisitor.d.ts
C# naming conventions (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#naming-conventions) dictate that you should use PascalCase for namespace, class, enum and public members. 
We currently don't generate C# code that conforms to these conventions, and when using it in a C# application it just feels... odd!
This change uses the `camelcase` library (confusing, but it seems to be the most popular one!) to generate C# code that conforms to these conventions.
=> feat(*): use pascal case by default for generated c# code

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
Update the C# code generator to add the new attribute `[AccordProject.Concerto.Identifier()]` to any identifying fields.
=> feat(*): add identifier attribute to generated c# fields

packages/concerto-cli/lib/commands.js, packages/concerto-cli/test/cli.js, packages/concerto-cli/test/models/version-in-comment.cto, packages/concerto-cli/test/models/version-in-comment2.cto
If you attempt to version the following CTO file:
```
/*
* something something namespace something something concerto
*/
namespace org.example@1.2.3
```
It silently updates the comment and ignores the actual namespace.
This change fixes that problem by improving the regex to only match `namespace <currentNamespace>`, and introduces a sanity test that will ensure that the updated CTO file parses to a metamodel with the new namespace.
=> fix(*): handle version when namespace in comments

packages/concerto-cli/index.js, packages/concerto-cli/test/cli.js, packages/concerto-tools/lib/codegen/fromJsonSchema/cto/inferModel.js, packages/concerto-tools/test/codegen/fromJsonSchema/cto/data/full.cto, packages/concerto-tools/test/codegen/fromJsonSchema/cto/data/schema.json, packages/concerto-tools/test/codegen/fromJsonSchema/cto/inferModel.js
- Relaxes error handling to quietly warn users of issues. This allows users to manually rectify issues.
- Basic support for `oneOf` alternatives (fallback to first alternative)
- Basic support for plain object types (defaults to `String` type, to allow serialisation.
=> feat(tools): improve JSON schema inference 

.github/pull_request_template.md, .github/workflows/publish.yml, contrib-notes/coding-guidelines.md, contrib-notes/submitting-pull-request.md
- Updates GitHub workflows to use main branch instead of master
- Updates docs to use main branch instead of master
- <ONE>
- <TWO>
=> chore(main) : update workflows and docs to use main branch

packages/concerto-tools/lib/codegen/fromJsonSchema/cto/inferModel.js, packages/concerto-tools/test/codegen/fromJsonSchema/cto/data/schema.json, packages/concerto-tools/test/codegen/fromJsonSchema/cto/inferModel.js
Improves inference of Concerto models from JSON Schema (and OpenAPI) definitions. Fixes a few bugs.
- Adds a job queue, so that any inline definition (sub-schema) can be processed after all top-level definitions.
- Stops using the `title` property to infer a type name. `title` is a short description field.
- Now replaces multiple occurrences of reserved characters in type names
- Includes a workaround for enum values that are not permitted in Concerto such as `1`, `true` (by adding a `_` prefix).
- Moves to a plain JS `Array` rather than `TypedStack`. This avoids edge cases to deal with the `null` item on the bottom of the stack.
=> feat(tools): support inference from JSON sub schemas

packages/concerto-metamodel/lib/metamodel.cto, packages/concerto-metamodel/lib/metamodel.json, packages/concerto-metamodel/lib/metamodelutil.js
The changes in #546 did not update the CTO representation of the metamodel we ship in the code, and so this change updates the CTO to match the new metamodel JSON. It also updates the metamodel JSON with the missing `@DotNetNamespace` decorator that has been removed.
This metamodel management process is broken and needs a revisit, but this will fix it for now.
=> fix(*): update metamodel cto to reflect metamodel json

packages/concerto-cli/lib/commands.js, packages/concerto-tools/lib/codegen/fromJsonSchema/cto/inferModel.js, packages/concerto-tools/test/codegen/fromJsonSchema/cto/inferModel.js
For schemas or OpenAPI definitions that include duplicate type names which only differ in the capitalization of the first character, the current behaviour creates a duplicate definition (which is invalid).
This change makes capitalisation of the first character an optional feature through the `capitalizeFirstLetterOfTypeName` option in the API, or the `--capitalizeFirst` flag in the CLI.
See `AccountSignatureProviders` and `accountSignatureProviders` in https://github.com/docusign/OpenAPI-Specifications/blob/master/esignature.rest.swagger-v2.1.json
=> fix(tools): don't capitalize types in JSON Schema inference by default 

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/lib/model/typed.js, packages/concerto-core/lib/serializer/instancegenerator.js, packages/concerto-core/test/data/parser/classdeclaration.scalaridentifier.cto, packages/concerto-core/test/introspect/classdeclaration.js, packages/concerto-core/test/serializer/instancegenerator.js
- Allows scalar types that extend `String` to be used as identifiers.
- Also fixes value generation for scalar types with validators
- Also fixes default value generation for scalar types with defaults
=> feat(core): allow scalar strings to be used as identifiers

packages/concerto-core/lib/introspect/property.js, packages/concerto-core/test/introspect/field.js, packages/concerto-core/test/introspect/property.js
A further fix to the new `scalar` feature. This fix properly unboxes Scalar properties.
=> fix(core): properly unbox scalar properties

packages/concerto-cli/test/cli.js, packages/concerto-tools/lib/codegen/fromcto/protobuf/protobufvisitor.js, packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap, packages/concerto-tools/test/codegen/codegen.js
Fixes the protobuf visitor so that it works with unversioned namespaces.
- Fix to visitor
- Adds a test to ensure all visitors are tested with a versioned CTO file as well as an unversioned CTO file
- <ONE>
- <TWO>
=> fix(tools) : protobuf generation with unversioned namespaces

package-lock.json, packages/concerto-core/types/lib/introspect/field.d.ts, packages/concerto-tools/lib/codegen/fromcto/avro/avrovisitor.js, packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap, packages/concerto-tools/types/index.d.ts, packages/concerto-tools/types/lib/codegen/codegen.d.ts, packages/concerto-tools/types/lib/codegen/fromcto/avro/avrovisitor.d.ts
- Uses the `@logicalType("timestamp-micros")` declaration for Concerto `DateTime` serialising the value to a `long`
- Only include the `$identifier` property for implicit identified models
- Regenerate the Typescript definitions
- [History of DateTime support in Avro](https://issues.apache.org/jira/browse/AVRO-739) 
=> fix(tools) define a logical type for timestamps

lerna.json, package-lock.json, package.json, packages/concerto-analysis/package.json, packages/concerto-cli/package-lock.json, packages/concerto-cli/package.json, packages/concerto-core/package-lock.json, packages/concerto-core/package.json, packages/concerto-cto/package-lock.json, packages/concerto-cto/package.json, packages/concerto-metamodel/package.json, packages/concerto-tools/package-lock.json, packages/concerto-tools/package.json, packages/concerto-types/package.json, packages/concerto-util/package-lock.json, packages/concerto-util/package.json, packages/concerto-vocabulary/package-lock.json, packages/concerto-vocabulary/package.json
The previous release (3.1.0) failed to create the PR that bumps the version number (because the branch was wrong at the time). The Action script has already been fixed but the packages still have the wrong version number.
=> chore(*): bump to 3.1.0

packages/concerto-cli/lib/commands.js, packages/concerto-core/lib/serializer.js, packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/test/concerto.js, packages/concerto-core/test/serializer.js, packages/concerto-core/test/serializer/jsongenerator.js, packages/concerto-core/types/lib/serializer/jsonpopulator.d.ts
This PR adds a new option to the `JSONGenerator` and `JSONPopulator` classes (and the `Serializer`) called `strictQualifiedDateTimes`. This allows client applications to drop support for unqualified, and ambiguous dates/datetimes.
This solves #552 in a backward-compatible way by not-allowing dates and date-times that don't have an offset. This also has the side-effect of making the `utcOffset` parameter only relevant to serialization; i.e. it becomes a rendering option. We always trust the offset provided when `strictQualifiedDateTimes` is `true`
When `strictQualifiedDateTimes` is `true`, only the following date-time formats are accepted.
- `YYYY-MM-DDTHH:mm:ssZ`
- `YYYY-MM-DDTHH:mm:ss.SZ`
- `YYYY-MM-DDTHH:mm:ss.SSZ`
- `YYYY-MM-DDTHH:mm:ss.SSSZ`
- `YYYY-MM-DDTHH:mm:ss+HH:mm`
- …
=> fix(core): deal with unqualified date times in local offsets

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/lib/introspect/decorated.js, packages/concerto-core/lib/introspect/scalardeclaration.js
Refactoring inefficient duplicate-checking nested `for` loops. The refactoring methodology follows @mttrbrts's (https://github.com/accordproject/concerto/pull/582) in replacing the nested `for` loops with ES6's `Set` structures.
Inefficiency discovery methodology: inspecting all loops in codebase.
=> fix(performance): refactoring inefficient duplication checking nested for loops

packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js, packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap
Updates the JSON Schema visitor to include an `anyOf` for polymorphic types.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> fix: JSON Schema generation improvements for base types #592

packages/concerto-cli/index.js, packages/concerto-cli/lib/commands.js, packages/concerto-tools/lib/codegen/fromcto/common/diagramvisitor.js, packages/concerto-tools/lib/codegen/fromcto/mermaid/mermaidvisitor.js, packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js, packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap, packages/concerto-tools/test/codegen/codegen.js, packages/concerto-tools/test/codegen/fromcto/plantuml/plantumlvisitor.js
Adds support for Composition and Aggregation relationships in UML output formats (Mermaid & PlantUML).
```mermaid
classDiagram
class `org.acme.Root` {
<< concept>>
+ `String` `firstName`
+ `String` `lastName`
+ `DateTime` `dob`
+ `Integer` `age`
+ `Double` `height`
+ `Children[]` `children`
}
`org.acme.Root` "1" o-- "1" `org.acme.Company` : company
`org.acme.Root` --|> `concerto@1.0.0.Concept`
class `org.acme.Person`
<< concept>> `org.acme.Person`
`org.acme.Person` --|> `concerto@1.0.0.Concept`
class `org.acme.Children` {
<< concept>>
+ `String` `name`
+ `Integer` `age`
+ `String` `hairColor`
+ `Boolean` `coolDude`
+ `String` `missing`
+ `Pet` `pet`
+ `String[]` `favoriteColors`
+ `Integer[]` `favoriteNumbers`
+ `String[]` `mixed`
+ `String[]` `arrayOfNull`
+ `String[]` `emptyArray`
+ …
```
=> feat(tools): add composition, aggregation relationships in UML

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/introspect/property.js, packages/concerto-core/lib/modelutil.js, packages/concerto-core/test/introspect/classdeclaration.js, packages/concerto-core/test/introspect/identifieddeclaration.js, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/test/introspect/property.js, packages/concerto-core/types/lib/modelutil.d.ts
Related to #581 
- Modifies the Core API to validate identifiers for Class Declarations, Properties, Enum values, and Namespace parts.
- Also, loosens a restriction in the code that prevented all user-defined properties beginning with a `$`. This now aligns with the metamodel.
- This is a bug fix, to address a gap in previously released code, however, it has the potential to break clients who relied upon the previous behaviour.
- The ID_REGEX is duplicated between the metamodel and the API, ideally, we should reuse the same definition. One solution is to validate the JSON AST against the metamodel using Concerto. However, for simplicity I've followed the existing pattern of implementing semantic checks in the introspection API.
=> fix(core): enforce identifier validation on AST JSON

packages/concerto-core/types/index.d.ts, packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
UUID support for csharp codegen.  Since UUID's are not supported globally by concerto, added a scalar type UUID with regex validation in `concerto.scalar` namespace.
=> feat(tools): csharp codegen uuid support

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
Signed-off-by: ragi.dayananda@docusign.com <ragi.dayananda@docusign.com>
- Nullable fields support for csharp codegen. Considering optional fields as nullable fields in csharp codegen.
- Add System. before Guid to avoid namespace collision or to prevent importing the System namespce.
=> feat(tools): csharp codegen nullable type support

packages/concerto-tools/lib/codegen/fromcto/csharp/csharpvisitor.js, packages/concerto-tools/test/codegen/fromcto/csharp/csharpvisitor.js
Signed-off-by: ragi.dayananda@docusign.com <ragi.dayananda@docusign.com>
- Support more csharp built in data types using `@DotNetType` annotation.
=> feat(tools): Support for more dotnet built-in types

.github/workflows/build.yml, package-lock.json, packages/concerto-core/package.json, packages/concerto-tools/package.json
Fixes the build by upgrading to a version of webpack which uses a more up-to-date version of `@types/estree`
=> fix(deps): upgrade to webpack 6.75.0

packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js, packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap
Today the PlantUML diagram is messy because PlantUML interprets all dots in fully-qualified names as packages names, and renders a box for the contained elements.
- Changes the string escaping function for PlantUML to escape the dots that appear in versioned namespaces to underscores
Note that boxes have been drawn for the `org` and `acme` and `test` namespaces, but not for the version of the `test@1.0.0` namespace.
=> fix: improve how plantuml namespaces are rendered

packages/concerto-tools/lib/codegen/fromcto/protobuf/protobufvisitor.js, packages/concerto-tools/test/codegen/fromcto/protobuf/data/apapProtocol.cto, packages/concerto-tools/test/codegen/fromcto/protobuf/data/concerto.metamodel.v0_4_0-expected.proto, packages/concerto-tools/test/codegen/fromcto/protobuf/data/org.accordproject.commonmark.v0_5_0-expected.proto, packages/concerto-tools/test/codegen/fromcto/protobuf/data/org.accordproject.party.v0_2_0-expected.proto, packages/concerto-tools/test/codegen/fromcto/protobuf/data/org.accordproject.protocol.v1_0_0-expected.proto, packages/concerto-tools/test/codegen/fromcto/protobuf/protobufvisitor.js
=> fix(tools): issue when converting a valid model to Protobuf

package-lock.json, packages/concerto-cli/lib/commands.js, packages/concerto-cli/package-lock.json, packages/concerto-cli/package.json, packages/concerto-cli/test/cli.js, packages/concerto-cli/test/models/person.cto, packages/concerto-core/lib/factory.js, packages/concerto-core/lib/serializer/instancegenerator.js, packages/concerto-core/test/models/test.js, packages/concerto-core/test/serializer/instancegenerator.js
- Throws an error if an id is provided to factory. newResource() that does not match the regex of the identifying field
- Fixes cli generate to generate an id that matches the regex if there is regex on the identifying field
- Had to update the tests using "CAR_123" since that id did not match the regex for VIN and now caused an error to throw.
=> fix(concerto): fix bugs when id field has regex

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/lib/model/identifiable.js, packages/concerto-core/lib/modelutil.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/test/models/animaltracking.js, packages/concerto-core/test/models/model.js, packages/concerto-core/test/serializer.js, packages/concerto-core/test/serializer/objectvalidator.js, packages/concerto-core/test/serializer/resourcevalidator.js
Better aligns the introspection API with the parser for fields that begin with a `$`.
Also, note that the existing behaviour is to add an additional field `$identifier` which shadows the value of any user-provided identifier field. This is by design because it allows client applications to resolve the identifier value without introspecting the model (which may not be available client-side). 
For example,
```cs
namespace test@1.0.0
concept test identified by name
{      o String name    }
```
The following payload is considered valid
```json
{    "$class": "test@1.0.0.test",     "name": "test",    "$identifier" : "test" }
```
- When a concept is identified by an explicitly named field (e.g. `concept p identified by x {...}`), we give the value of that field primacy.
- We explicitly list …
=> fix(core): disallow reserved fields in JSON serialization

package-lock.json, packages/concerto-core/types/lib/model/identifiable.d.ts, packages/concerto-core/types/lib/modelutil.d.ts, packages/concerto-core/types/lib/serializer/jsongenerator.d.ts, packages/concerto-core/types/lib/serializer/jsonpopulator.d.ts, packages/concerto-core/types/lib/serializer/resourcevalidator.d.ts, packages/concerto-cto/lib/parser.js, packages/concerto-cto/lib/parser.pegjs, packages/concerto-cto/lib/printer.js, packages/concerto-cto/test/cto/bad/map.bad.cto, packages/concerto-cto/test/cto/bad/map.bad.identifiers.cto, packages/concerto-cto/test/cto/map.cto, packages/concerto-cto/test/cto/map.json, packages/concerto-cto/test/parserMain.js
The implementation of the map declaration feature will be delivered incrementally through a phased approach. The first phase involves updating the parser grammar, & enabling both Parse and Print for map types. As part of this process, test data for both the cto and ast representation of a map declaration is added to test the print and parse functionalities.
At its core, a `MapDeclaration` consists of one `MapKeyType` and a general `AggregateValueType`, which may in some cases be specialized to an `AggregateRelationshipValueType`—both of which may be annotated, as too can the parent declaration.
For more information on the design specification see [here](https://github.com/accordproject/concerto/wiki/Aggregate-Types-Design)
- <ONE> Updated Parser.pegjs
- <TWO> Updated Printer
- <THREE> …
=> feat(*): MapDeclaration Parse & Print

packages/concerto-vocabulary/lib/vocabularymanager.js, packages/concerto-vocabulary/test/org.acme.cto, packages/concerto-vocabulary/test/vocabularymanager.js
When adding vobulary terms as decorators to the model, `englishMissingTermGenerator` failed for Scalars. Fixed the issue and modified a test.
- Optionally chained the function call to `getProperties` for the `declarations` object. As Scalars don't have properties, the function won't get called.
=> bug(vocabulary): fix for vocabulary management for ScalarDeclaration

packages/concerto-core/lib/modelutil.js, packages/concerto-core/lib/serializer.js, packages/concerto-core/lib/serializer/instancegenerator.js, packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/jsonpopulator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/lib/serializer/valuegenerator.js, packages/concerto-core/messages/en.json, packages/concerto-core/test/data/model/concept.cto, packages/concerto-core/test/model/concept.js, packages/concerto-core/test/serializer.js, packages/concerto-core/test/serializer/instancegenerator.js, packages/concerto-core/test/serializer/resourcevalidator.js, packages/concerto-core/test/serializer/valuegenerator.js, packages/concerto-core/types/lib/modelutil.d.ts, packages/concerto-core/types/lib/serializer/instancegenerator.d.ts, packages/concerto-core/types/lib/serializer/jsongenerator.d.ts, packages/concerto-core/types/lib/serializer/jsonpopulator.d.ts, packages/concerto-core/types/lib/serializer/resourcevalidator.d.ts
This change adds basic serialisation of a map in the form of <string, string>. Further type variations will follow in subsequent PR.
For more information on the design specification see [here](https://github.com/accordproject/concerto/wiki/Aggregate-Types-Design)
- Issue #447
=> feat(map): add serialisation for map<string, string>

packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/test/modelmanager.js
Updates the `BaseModelManager.filter` method to update all the imports in the model manager based on the types that were removed by calls to `ModelFiler.filter`. 
- ModelFile.filter method updated to return an array of the types that were removed by the filter predicate
- BaseModelManager.filter method updated to remove imports of removed types
- Unit test
- The change to ModelFile.filter to take `removedDeclarations` as an extra argument is technically a breaking change however if we assume that the only caller of this function is BaseModelManager then we could argue that this is a pure bug fix.
- I'm uncertain about this behaviour: `ModelFiles with no declarations after filtering will be removed.` — I suspect this could break wildcard imports when Concerto is used with `strict:false`. …
=> fix(filter) : remove imports of filtered types

packages/concerto-core/lib/introspect/introspector.js, packages/concerto-core/test/introspect/introspector.js
##Description
Introspector.getClassDeclarations should return ClassDeclarations only. This PR filters on declarations of type MapDeclaration.
=> feat(introspector): getClassDeclarations filters map declarations

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/types/lib/introspect/modelfile.d.ts
This PR adds the API functionality `ModelFile.getClassDeclarations`, which returns Declarations of type `ClassDeclaration` only.
=> feat(ModelFile): model file class declarations

packages/concerto-core/lib/introspect/mapkeytype.js
There may be scenarios where a declaration associated with a MapKeyType may not yet be available for reference within the model file, leading to an Edge case where the Key Types value cannot be set. In order to avoid this erroneous behaviour, the Type is set directly from the AST instead of the associated Declaration instance.
=> feat(maps): assign key type from ast

package-lock.json, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/data/decoratorcommands/test.cto, packages/concerto-core/test/data/decoratorcommands/web.json, packages/concerto-core/test/decoratormanager.js
Fixes the `DecoratorManager` to allow it to apply decorators to models containing scalars.
- Adds a check for class declarations that do not contain a `properties` member (like scalars)
- Updates the unit test to include a scalar and a decorator command set that applies a decorator to a scalar
- @Jonathan-Casey we should add a similar unit test for Map declarations. We will have to think about how to add decorators to the key or value properties of a map.
=> fix(decoratormanager) applying decorators to a scalar using decorator sets

packages/concerto-analysis/src/compare-config.ts, packages/concerto-analysis/src/compare-utils.ts, packages/concerto-analysis/src/compare.ts, packages/concerto-analysis/src/comparer.ts, packages/concerto-analysis/src/comparers/index.ts, packages/concerto-analysis/src/comparers/scalar-declarations.ts, packages/concerto-analysis/test/fixtures/scalar-added.cto, packages/concerto-analysis/test/fixtures/scalar-changed-extends.cto, packages/concerto-analysis/test/fixtures/scalar-number-validator-added.cto, packages/concerto-analysis/test/fixtures/scalar-number-validator-changed-lowercompat.cto, packages/concerto-analysis/test/fixtures/scalar-number-validator-changed-uppercompat.cto, packages/concerto-analysis/test/fixtures/scalar-number-validator-changed-upperincompat.cto, packages/concerto-analysis/test/fixtures/scalar-number-validators.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-added.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-changed.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-length-added.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-length-changed-lowercompat.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-length-changed-lowerincompat.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-length-changed-uppercompat.cto, packages/concerto-analysis/test/fixtures/scalar-string-validator-length-changed-upperincompat.cto, packages/concerto-analysis/test/fixtures/scalar-string-validators.cto, packages/concerto-analysis/test/unit/compare-utils.test.ts, packages/concerto-analysis/test/unit/compare.test.ts
Adds support for analysing the changes between scalars in model files to the concerto-analysis package.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> feat(analysis) scalar change analysis

packages/concerto-core/lib/serializer/jsongenerator.js, packages/concerto-core/lib/serializer/resourcevalidator.js, packages/concerto-core/test/serializer/maptype/serializer.js
Removes the $class reference found in MapDeclarations.
=> feat(map): remove class reference in Maps

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/data/decoratorcommands/web.json, packages/concerto-core/test/decoratormanager.js
Updates decorator manager to allow command targets to use unversioned namespaces.
- Update apply decorator
- Update validate decorator command
- <ONE>
- <TWO>
=> feat(decoratormanager) add support for unversioned namespaces in decorator command set target

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/decoratormanager.js, packages/concerto-core/types/lib/decoratormanager.d.ts
Updates the DecoratorManager API for backwards compatibility.
- Changes the static DecoratorManager.falsyOrEquals method to accept either a single string value, or an array or strings
- <ONE>
- <TWO>
=> chore(decoratormanager) API backwards compat

package-lock.json, package.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/package-lock.json, packages/concerto-core/package.json, packages/concerto-core/test/data/decoratorcommands/invalid-command.json, packages/concerto-core/test/data/decoratorcommands/invalid-model.json, packages/concerto-core/test/data/decoratorcommands/invalid-target-declaration.json, packages/concerto-core/test/data/decoratorcommands/invalid-target-namespace.json, packages/concerto-core/test/data/decoratorcommands/invalid-target-properties.json, packages/concerto-core/test/data/decoratorcommands/invalid-target-property-properties.json, packages/concerto-core/test/data/decoratorcommands/invalid-target-property.json, packages/concerto-core/test/data/decoratorcommands/invalid-type.json, packages/concerto-core/test/data/decoratorcommands/test.cto, packages/concerto-core/test/data/decoratorcommands/web.json, packages/concerto-core/test/decoratormanager.js, packages/concerto-core/types/lib/decoratormanager.d.ts, packages/concerto-cto/package.json, packages/concerto-util/package.json, packages/concerto-util/test/logger.js, packages/concerto-vocabulary/lib/vocabularymanager.js, packages/concerto-vocabulary/test/__snapshots__/vocabularymanager.js.snap
Updates the decorator command set model to allow a decorator command target to reference multiple properties.
- Update model
- Update validation
- Update apply decorator
- Update dependencies
- Update tests
- Version 0.3.0 of decorator command set model (needs to be published to https://models.accordproject.org)
Here is an example command that targets an array of properties.
```
namespace test@1.0.0
scalar SSN extends String
@Editable
concept Person {
@Custom
o String firstName
o String lastName
o String bio
o SSN ssn
o String address1
o String address2
o Integer zip
}
```
```
{
"$class" : "org.accordproject.decoratorcommands@0.3.0.Command",
"type" : "UPSERT",
"target" : {
"$class" : "org.accordproject.decoratorcommands@0.3.0.CommandTarget",
"namespace" : "test",
"declaration" : "Person", …
```
=> feat(core): decorator multi property

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/decoratormanager.js, packages/concerto-core/types/lib/decoratormanager.d.ts
Adds `DecoratorManager.validate` method to perform structural validation of decorator command sets.
- Adds new static method to DecoratorManager: refactoring of existing code that was in the `decoratorModels` method.
- Adds test cases
- <ONE>
- <TWO>
=> feat(decoratormanager) add validate method

packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/introspect/mapdeclaration.js, packages/concerto-core/test/introspect/mapdeclaration.js
Add property based flag to `ModelManager` options as an alternative to setting process.env `ENABLE_MAP_TYPE='true`. 
**This change is temporary and will be removed on full release of Map Type.**
`modelManager = new ModelManager({enableMapType: true});
`
=> feat(map): add property based flag

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/modelmanager.js, packages/concerto-core/types/lib/modelmanager.d.ts
Add JSDoc for  ModelManager `enableMapType` option
=> feat(*): Add JSDoc for  ModelManager `enableMapType` option 

packages/concerto-core/lib/introspect/mapkeytype.js, packages/concerto-core/lib/introspect/mapvaluetype.js, packages/concerto-core/lib/modelutil.js, packages/concerto-core/test/data/parser/mapdeclaration/base.cto, packages/concerto-core/test/data/parser/mapdeclaration/mapdeclaration.badkey.imported.thing.cto, packages/concerto-core/test/data/parser/mapdeclaration/mapdeclaration.goodkey.imported.scalar.cto, packages/concerto-core/test/data/parser/mapdeclaration/mapdeclaration.goodvalue.imported.thing.cto, packages/concerto-core/test/introspect/mapdeclaration.js, packages/concerto-core/types/lib/decoratormanager.d.ts, packages/concerto-core/types/lib/introspect/mapkeytype.d.ts, packages/concerto-core/types/lib/introspect/mapvaluetype.d.ts, packages/concerto-core/types/lib/modelutil.d.ts
Adds logic to support declaration of Map Key Type as an Imported Type. Additional test cases also added.
=> feat(map): Support Map Key Type Imports

packages/concerto-core/lib/introspect/field.js, packages/concerto-core/test/data/parser/classdeclaration.scalararray.cto, packages/concerto-core/test/introspect/classdeclaration.js, packages/concerto-core/test/introspect/scalars.js
- added array modifier for scalar field unboxing condition
- Issue #745
=> fix(core):  missing array modifier for scalar fields

package-lock.json, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/data/decoratorcommands/test.cto, packages/concerto-core/test/data/decoratorcommands/web.json, packages/concerto-core/test/decoratormanager.js
Fixes logic and adds a test.
- Fix logic in DecoratorManager
- Add some tests for combinations of property / properties with and without types.
- <ONE>
- <TWO>
=> fix(decoratormanager): apply decorators to properties without a type

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/messages/en.json, packages/concerto-core/test/introspect/classdeclaration.js
Raises an error if the declaration ast has an invalid properties field.
- Since rest of the `process` method expects `properties` to be an array we add a check for that.
=> fix(class-declaration): throw with undefined ast properties

packages/concerto-core/lib/introspect/classdeclaration.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/test/introspect/classdeclaration.js, packages/concerto-core/test/introspect/modelfile.js
This logic doesn't need to run for each declaration in the class. It basically calls the model file and fetches declarations and creates a set. There is nothing special about the particular declaration within this logic.
- Moved unique name check logic to model file
- Updated the tests (move the tests from class declaration to model file as well)
=> refactor(declarations): move declaration uniqueness check to model file

package-lock.json, packages/concerto-core/lib/introspect/modelfile.js
We don't use `declarationNames` array after doing bunch of uniqueness check. Even though we collect all non-unique names in the model, we only add the name of the first one in the error message. So this refactor removed the usage of the array and uses only the `Set`. If there is a non-unique name in the model file, it immediately throws.
- Use only a `Set` while checking uniqueness
- Issue #785 
- Pull Request #794
=> perf(core): don't use arrays to check uniqueness

package-lock.json, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/introspect/decorated.js, packages/concerto-core/lib/introspect/decorator.js, packages/concerto-core/lib/introspect/introspector.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/lib/introspect/validator.js, packages/concerto-core/types/lib/introspect/decorated.d.ts, packages/concerto-core/types/lib/introspect/decorator.d.ts, packages/concerto-core/types/lib/introspect/introspector.d.ts, packages/concerto-core/types/lib/introspect/validator.d.ts
- Edited JSDoc of `accept` methods in introspect classes to mark them as `public`.
- Generated changes in typescript definitions in `lib/types`.
=> fix(core): private `accept` methods in introspect classes - I839

packages/concerto-core/test/decoratormanager.js
- Added `__dirname` keyword as prefix of every path of the .cto file
- <img width="1280" alt="Screenshot 2024-04-06 at 9 26 05 PM" src="https://github.com/accordproject/concerto/assets/99127578/fc447794-6668-41b8-964b-db84abcf2837">
=> Fixed no such file or directory error in decoratormanager.js Test File

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/package.json, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/types/lib/basemodelmanager.d.ts
- TODO marked
- aliasImport handling in runtime separated from rest code to prevent breaking changes
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> feat(alias-import): update runtime classes to understand import aliasing

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratorextractor.js, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/data/decoratorcommands/extract-test-dcs.json, packages/concerto-core/test/data/decoratorcommands/extract-test-vocab.json, packages/concerto-core/test/data/decoratorcommands/extract-test.cto, packages/concerto-core/test/decoratormanager.js, packages/concerto-vocabulary/lib/vocabulary.js, packages/concerto-vocabulary/test/vocabulary.js
Added methods to extract vocab/non-vocab decorators, fixed vocabulary parsing bugs, and exposed locale validation method.
- <ONE> Added new methods to extract vocab or non-vocab decorators from model
- <TWO> Fixed some minor bugs related to vocabulary parsing
- <THREE> Exposed method to validate locale
=> feat(decorator): added new methods to extract vocab or non-vocab decorators from model

packages/concerto-core/changelog.txt, packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/introspect/modelfile.js, packages/concerto-core/test/introspect/introspector.js, packages/concerto-core/test/introspect/modelfile.js, packages/concerto-core/types/lib/basemodelmanager.d.ts
- Alias import test-cases  for introspector test module
- Issue #867 
- Issue #868
=> feat(alias-import): added test case for introspector

packages/concerto-analysis/src/compare-config.ts, packages/concerto-analysis/src/comparers/properties.ts, packages/concerto-analysis/test/fixtures/field-local-type-change-a.cto, packages/concerto-analysis/test/fixtures/field-local-type-change-b.cto, packages/concerto-analysis/test/unit/compare-config.test.ts, packages/concerto-analysis/test/unit/compare.test.ts, packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/basemodelmanager.js, packages/concerto-core/lib/modelmanager.js, packages/concerto-core/types/lib/basemodelmanager.d.ts, packages/concerto-core/types/lib/modelmanager.d.ts
This pull request deals with analyser rules for aliased types in concerto. 
- Issue #869
=> feat(import-alias):patch change for aliased imported types

packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/decoratormanager.js
If we pass a model manager which has maptype enabled to dcs manager's decorate method we need the new model managers generated and used inside the decorate and validate methods of dcs managers to enable map types as well.
=> fix(dcs): enableMapTypes in internal modelmanagers in dcsmanager

package-lock.json, packages/concerto-analysis/package.json, packages/concerto-core/package.json, packages/concerto-cto/package.json, packages/concerto-types/package.json, packages/concerto-vocabulary/package.json
Update the versions of internal dependencies to the latest. In particular this allows `concerto-core` to depend the lastest version of `concerto-cto` that in turn depends on a version of `concerto-metamodel` that no longer depends on a vulnerable version of `axios`. We'll need to update the concerto-codegen deps later too.
=> chore(versions): use latest versions of other concerto packages

package-lock.json, package.json, packages/concerto-analysis/package.json, packages/concerto-core/package.json, packages/concerto-cto/package.json, packages/concerto-types/package.json, packages/concerto-vocabulary/package.json
Signed-off-by: muhammed-abdulkadir <muhammed.abdulkadir@docusign.com>
- Fix deps issue where concerto packages need to be 1 level higher than the rest, this change ensure the current build is used across all packages
=> feat(*): update concerto deps to use same build

packages/concerto-core/lib/decoratormanager.js
Pass import aliasing option to model manager in decorator set manager
- <ONE>
- <TWO>
- <ONE>
- <TWO>
=> fix(bug): pass model manager options to new mm in dcs manager

.github/workflows/close-stale.yml
- Marks issues as stale after 60 days of inactivity and closes 10 days later.
- Marks PRs as stale after 15 days of inactivity and closes 10 days later.
-  Exempts anything in v4.0 milestone from being closed
- Uses https://github.com/marketplace/actions/close-stale-issues
- Please provide opinions on the timing for when an issue/PR is stale or closed. I used my best judgement here but would like to hear from the community. Also anything else we should exempt besides the v4.0 milestone items.
- Issue https://github.com/accordproject/technical-steering-committee/issues/52
=> feat: add GH action for closing stale prs and issues 

package-lock.json, package.json, packages/concerto-analysis/package.json, packages/concerto-core/package.json, packages/concerto-cto/package.json, packages/concerto-cto/webpack.config.js, packages/concerto-types/package.json, packages/concerto-util/package.json, packages/concerto-vocabulary/package.json
`npm ci` and `npm run build` executed successfully.
`concerto-core` now should use `concerto-util@3.20.1` now thus making the browser build stable
=> fix(utils): fix browser build for concerto-util

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/types/lib/decoratormanager.d.ts, packages/concerto-vocabulary/lib/vocabularymanager.js, packages/concerto-vocabulary/test/__snapshots__/vocabularymanager.js.snap
Expose migrateTo and canMigrate methods from DecoratorManager. These were previously private methods.
=> chore(dcs): expose canMigrate and migrateTo methods from DecoratorManager

packages/concerto-core/lib/introspect/scalardeclaration.js, packages/concerto-core/test/introspect/scalardeclaration.js
Closes #994 
- Added validation to reject scalar declarations using primitive type names
- Implemented unit tests for scalar name validation
- Updated error messaging with proper source location
*Reproduction of issue #994 scenario: Error when using `String` as scalar name in test model from original report*
- Fixes potential namespace collisions with primitive types
- Maintains backward compatibility (no breaking changes)
- Console warnings in test output are pre-existing issues
=> fix(scalar): add validation for scalar declarations

packages/concerto-core/src/serializer/jsonpopulator.js, packages/concerto-core/test/serializer/jsonpopulator.js
- Modified constructor logic to default `strictQualifiedDateTimes` to `true` if not provided.
- Updated JSDoc to document the new parameter: `@param {boolean} [strictQualifiedDateTimes=true] - Only allow fully-qualified date-times with offsets`.
- This change enforces stricter validation by default, which may affect existing code relying on non-fully-qualified date-time values.
=> BREAKING CHANGE(serializer): make strictQualifiedDateTimes default to true

packages/concerto-core/lib/introspect/numbervalidator.js, packages/concerto-core/lib/introspect/stringvalidator.js, packages/concerto-core/test/data/model/dependencies/base/base.cto, packages/concerto-core/test/data/parser/classdeclaration.scalararray.cto, packages/concerto-core/test/data/parser/classdeclaration.scalaridentifier.cto, packages/concerto-core/test/data/parser/scalardeclaration.ssn.cto, packages/concerto-core/test/introspect/numbervalidator.js, packages/concerto-core/test/introspect/scalardeclaration.js, packages/concerto-core/test/introspect/stringvalidator.js, packages/concerto-cto/test/cto/scalar.cto, packages/concerto-cto/test/cto/scalar.json
Fixed default values not validated against meta model properties (E.g., Regex, Length, Range)
- <ONE> Validating `String` properties with default values against the `length` and `regex` meta properties.
- <TWO> Validating `Integer`, `Double` and `Long` properties with default Values against the `range` meta property.
- <ONE> There was an invalid Regex expression in the data files used for testing, I changed it to a correct one.
NA
- Issue #1010
=> Fixing Default Values Ignoring Meta properties.

packages/concerto-analysis/src/compare-config.ts, packages/concerto-analysis/src/comparers/properties.ts, packages/concerto-analysis/src/comparers/scalar-declarations.ts, packages/concerto-analysis/test/fixtures/optional-to-required-a.cto, packages/concerto-analysis/test/fixtures/optional-to-required-b.cto, packages/concerto-analysis/test/fixtures/property-added.cto, packages/concerto-analysis/test/fixtures/property-default-value-added.cto, packages/concerto-analysis/test/fixtures/property-default-value-changed.cto, packages/concerto-analysis/test/fixtures/required-to-optional-a.cto, packages/concerto-analysis/test/fixtures/required-to-optional-b.cto, packages/concerto-analysis/test/fixtures/scalar-default-value-added.cto, packages/concerto-analysis/test/fixtures/scalar-default-value-changed.cto, packages/concerto-analysis/test/unit/compare-config.test.ts, packages/concerto-analysis/test/unit/compare.test.ts
This PR addresses issue #719 by adding logic to detect changes in the following scenarios:
Each change is covered by **unit tests** to ensure correctness. This ensures that the `concerto-analysis` package correctly identifies and reports these changes, improving the accuracy of model comparisons.
---
- All new changes are covered by unit tests.
- Verified against sample `.cto` files to ensure accurate detection of changes.
---
NA
NA
- Issue #719
=> fix(analysis): detect changes for various model modifications

package-lock.json, package.json, packages/concerto-linter/.eslintignore, packages/concerto-linter/.eslintrc.yml, packages/concerto-linter/HEADER.md, packages/concerto-linter/README.md, packages/concerto-linter/jest.config.js, packages/concerto-linter/package.json, packages/concerto-linter/src/index.ts, packages/concerto-linter/src/rulesets/core-ruleset.ts, packages/concerto-linter/src/rulesets/naming-ruleset.ts, packages/concerto-linter/test/fixtures/ENUM_Constans-invaild.cto, packages/concerto-linter/test/fixtures/ENUM_Constans-vaild.cto, packages/concerto-linter/test/fixtures/declarations-valid-camelCase.cto, packages/concerto-linter/test/fixtures/declarations-violate-camelCase.cto, packages/concerto-linter/test/fixtures/properties-valid-PascalCase.cto, packages/concerto-linter/test/fixtures/properties-violate-PascalCase.cto, packages/concerto-linter/test/rules/naming-ruleset.test.ts, packages/concerto-linter/tsconfig.build.json, packages/concerto-linter/tsconfig.json
Introduces `concerto-linter` package with initial naming rules implementation.  
- Added new `concerto-linter` package with base configuration matching Concerto standards  
- Implemented first set of naming rules (from #1021) including:
- camelCase for all declarations
- PascalCase for all properties
- UPPER_SNAKE_CASE for enum constants
- Added unit tests covering all naming rules  
- Established `lintAST` entry point (`packages/concerto-linter/src/index.ts`):  
- **Input**: Concerto model JSON AST as string   
- **Output**: `ISpectralLintResult[]` array containing:  
- Rule violations with location details  
- Severity levels (error/warning/info)  
- Paths to problematic 
- **`lintAST` is preliminary**: requires further development for:  
- lintAST input: Currently takes JSON AST as …
=> feat: Add concert-linter package structure and naming convention rules

package-lock.json, packages/concerto-linter/README.md, packages/concerto-linter/package.json, packages/concerto-linter/src/config-loader.ts, packages/concerto-linter/src/index.ts, packages/concerto-linter/test/rules/naming-ruleset.test.ts
- **Updated linter API**  
- Accepts CTO models as both strings and plain AST objects
- **Implemented extensible ruleset configuration**  
- Supports `.yaml`, `.yml`, `.json`, and `.js` files
- **Added capabilities to:**
- Enable/disable individual rules
- Define custom rules
- Modify rule severity levels
- Extend base ruleset
- **Automated ruleset discovery**  
Searches the project directory for:
```js
const SPECTRAL_RULESET_FILES = [
'.spectral.yaml',
'.spectral.yml',
'.spectral.json',
'.spectral.js'
];
- **Path Override Support**
- Explicit ruleset path can be passed to the `lint()` function.
> For more information, refer to the **README** file.
- A default ruleset will be published as a `concerto-linter-default-ruleset` subpackage 
- Users can extend the core rules using the `extends` …
```
=> feat(linter): Add configurable linter support

packages/concerto-core/lib/decoratormanager.js, packages/concerto-types/scripts/codegen.js, packages/concerto-types/src/generated/unions/concerto@1.0.0.ts, packages/concerto-types/src/generated/unions/org.accordproject.decoratorcommands@0.4.0.ts
Modifed code generation script to include DCS Concerto model types
- <ONE>Modify code generation script to include DCS Concerto model types
- Issue #943
=> fix : Modify code generation script to include DCS Concerto model types

packages/concerto-core/api.txt, packages/concerto-core/changelog.txt, packages/concerto-core/lib/dcsconverter.js, packages/concerto-core/lib/decoratormanager.js, packages/concerto-core/test/dcsconverter.js, packages/concerto-core/test/decoratormanager.js, packages/concerto-core/types/lib/dcsconverter.d.ts, packages/concerto-core/types/lib/decoratormanager.d.ts
This PR implements YAML to JSON conversion support for Decorator Command Sets (DCS), completing the bidirectional transformation feature.
- Implemented `yamlToJson()` function in `lib/dcsconverter.js` for converting simplified YAML DCS into JSON
- Exposed `yamlToJson()` via `DecoratorManager`
- Type definitions updated in `dcsconverter.d.ts` and `decoratormanager.d.ts`
- Comprehensive unit tests in `test/dcsconverter.js` and `test/decoratormanager.js`
---
=> feat(concerto-core): implement YAML to JSON conversion for DCS

packages/concerto-linter/default-ruleset/src/functions/check-length-validator.ts, packages/concerto-linter/default-ruleset/src/pascal-case-decorators.ts, packages/concerto-linter/default-ruleset/src/property-string-length.ts, packages/concerto-linter/default-ruleset/src/ruleset-main.ts, packages/concerto-linter/default-ruleset/src/scalar-string-length.ts
This PR adds **three new default rulesets** to our linter based on the discussion at the WG for #1051  and the subsequent approval.
1. **String Length**  
- All `String` fields, whether **properties** or **scalar values**, must have a defined length validator.  
- This ensures better data validation and consistency.
2. **Decorator Names Should Follow PascalCase**  
3. **Reserved Keywords Used as Names**  
- Prevents using reserved Concerto model keywords as declaration or property or decorator names.  
- Reserved keywords include:  
```
String, Double, Integer, Long, DateTime, Boolean, scalar, concept, enum, asset, participant, transaction, event, map
```
---
=> feat(linter): Add string length, PascalCase decorators, reserved keywords rules

packages/concerto-linter/jest.config.js, packages/concerto-linter/src/config-loader.ts, packages/concerto-linter/src/index.ts, packages/concerto-linter/test/unit/configLoader.test.ts, packages/concerto-linter/test/unit/formatResults.test.ts, packages/concerto-linter/test/unit/lintModel.test.ts, packages/concerto-linter/test/unit/loadRuleset.test.ts
At this PR:
* The refactor of the linter output to follow the JSON format that was suggested at #1050.
* Enable the filtering for the results of the linter by namespace to control it; by default the exclusion list will be \[`concerto.*`, `org.accordproject.*`] and it will be configurable.
This was achieved by editing the `lintModel` parameters to receive an option object where you can pass the `excludeNamespaces` if you want to override the default one.
```ts
/**
* Lints Concerto models using Spectral and Concerto rules.
*
* @param {string | object} model - The Concerto model to lint, either as a CTO string or a parsed AST object.
* @param {options} [config] - Linting configuration options.
* @param {string} [config.ruleset] - Path to a custom Spectral ruleset or 'default' to use the …
```
=> feat(linter): refactor lintModel output shape & add namespace filtering
