accordproject/concerto

- api.txt
- changelog.txt
- index.js
- lib/baseexception.js
- lib/basefileexception.js
- lib/introspect/eventdeclaration.js
- lib/introspect/illegalmodelexception.js
- lib/introspect/parseexception.js
- lib/serializer/validationexception.js
- lib/typenotfoundexception.js
- package-lock.json
- test/baseexception.js
- test/basefileexception.js
- test/introspect/illegalmodelexception.js
- test/introspect/parseexception.js
- test/typenotfoundexception.js
This PR provides improvements to the composer-concerto error handling:
- Adds `fileName` field to `fileLocation` in errors when possible
- Adds `component` field to errors which defaults to `composer-concerto` but can let consumers set their own.
- Fixes to JSDoc for errors
1.
2.
3.
4.
> feature(Errors) add information to errors & fix JSDoc

- package.json
- test/baseexception.js
- test/basefileexception.js
- test/introspect/illegalmodelexception.js
- test/typenotfoundexception.js
> fix(deploy) package name should have the accordproject prefix

- HEADER.md
- lib/tools/notes.md
- package.json
> chore(license) fixes licchk for markdown

- README.md
<OVERALL SUMMARY OF PULL REQUEST>
- add downloads badge
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
> docs: add downloads badge

- package-lock.json
- package.json
- packages/concerto-cli/package.json
- packages/concerto-core/package.json
- packages/concerto-tools/package-lock.json
- packages/concerto-tools/package.json
- packages/concerto-tools/test/codegen/fromcto/loopback/loopbackvisitor.js
Update the package dependencies to be consistent across root lerna package.json and across sub-packages.
> (chore) update dependencies to fix lerna hoisting

- README.md
Add hyperlinks to Table of Contents in README and changed Types to a table
Hyperlinks, Tables
- Preview in Markdown and test
> Added hyperlinks to TOC and table for types

- packages/concerto-core/package.json
- packages/concerto-core/types/index.d.ts
- packages/concerto-core/types/tsconfig.json
- packages/concerto-tools/package.json
- packages/concerto-tools/types/index.d.ts
- packages/concerto-tools/types/tsconfig.json
Signed-off-by: Giacomo Minighin <giacomo.minighin@gmail.com>
- created typescript definitions
> (feat) typescript definitions

- .travis.yml
- package-lock.json
- package.json
> fix(CI) lerna bootstrap rather than npm install

- .travis/deploy.sh
> fix(CI) deploy as public package

- README.md
- packages/concerto-cli/README.md
- packages/concerto-cli/package.json
- packages/concerto-core/README.md
- packages/concerto-core/package.json
- packages/concerto-tools/README.md
- packages/concerto-tools/package.json
> fix(doc) READMEs and descriptions

- packages/concerto-cli/README.md
- packages/concerto-cli/index.js
- packages/concerto-cli/lib/commands.js
- packages/concerto-cli/test/cli.js
- packages/concerto-cli/test/data/sample1.json
- packages/concerto-cli/test/data/sample2.json
Add `concerto validate` command.
> feature(CLI) Add cicero validate

- README.md
- package.json
- packages/concerto-cli/package.json
- packages/concerto-cli/test/cli.js
> fix(test) Add test & coverage for cicero-cli

- .travis.yml
- packages/concerto-cli/package.json
- packages/concerto-core/package.json
- packages/concerto-tools/package.json
> fix(CI) Add code coverage reporting to Travis Build

- README.md
Added more (missing?) hyperlinks, better syntax highlighting (JS instead of plain code)
Signed-off-by: Bharat123rox <bharatraghunthan9767@gmail.com>
> docs(README): Add hyperlinks, better syntax highlighting

- README.md
Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>
<OVERALL SUMMARY OF PULL REQUEST>
**Changes**
- Centering the title 
- Centering the badges
**Related Issues**
* Issue #79
* Pull Request #97
> doc(Readme) : Centering title

- contrib-notes/coding-guidelines.md
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>
• 'the' appearing twice consecutively in a sentence
• 'is update' to 'is updated'
• 'comitter' to 'committer'
Changed some spellings
> Fixed some grammatical errors / typos

- DEVELOPERS.md
- Fixed typo errors in `DEVELOPERS.md`
- Issue #115
> Fixed typo

- package-lock.json
- packages/concerto-cli/index.js
> fix(CLI) Print help if no command passed to CLI

- .travis.yml
- package-lock.json
- packages/concerto-cli/package.json
- packages/concerto-tools/package.json
> chore(build) Add Windows build to CI

- package-lock.json
- packages/concerto-core/lib/modelmanager.js
- packages/concerto-core/package.json
> fix(win) Normalize Windows path before writing models to disk

- README.md
Fix small issue with package link to markdown editor in Readme
> fix(readme): fix link to markdown editor package

- packages/concerto-cli/lib/commands.js
- packages/concerto-core/api.txt
- packages/concerto-core/changelog.txt
- packages/concerto-core/index.js
- packages/concerto-core/lib/modelloader.js
- packages/concerto-core/test/modelloader.js
- packages/concerto-core/test/modelmanager.js
> refactor(core) Add utility for loading a model manager

- packages/concerto-core/lib/introspect/parser.js
- packages/concerto-core/lib/introspect/parser.pegjs
Further cleanups of Concerto parser.
> fix(grammar) Remove a few more unused things in pegjs grammar

- packages/concerto-core/api.txt
- packages/concerto-core/changelog.txt
- packages/concerto-core/lib/modelloader.js
- packages/concerto-core/lib/modelmanager.js
- packages/concerto-core/test/modelloader.js
- packages/concerto-core/types/index.d.ts
> feature(core) Add convenience function to load model manager from model files objects

- package-lock.json
- packages/concerto-core/lib/logger.js
- packages/concerto-core/package.json
Catch any errors creating the log directory.
> feat for #199 - protect log creation from read-only fs

- package-lock.json
- packages/concerto-cli/index.js
- packages/concerto-cli/lib/commands.js
- packages/concerto-cli/test/cli.js
- packages/concerto-cli/test/models/contract.cto
- packages/concerto-core/api.txt
- packages/concerto-core/changelog.txt
- packages/concerto-core/lib/modelloader.js
- packages/concerto-core/scripts/versionchecker.js
- packages/concerto-core/test/scripts/versionchecker.js
- Add `offline` option to `ModelLoader` utility class
- Add `--offline` option to CLI
- Allow increment to patch number on version checker for API / changelog
> fix(cli) Add offline option to modelloader and CLI

- README.md
- package.json
- Cleans up remaining travis bits
- Use a GitHub action badge in the README
> chore(admin) Change status badge to github workflow

- package-lock.json
- packages/concerto-core/package.json
Upgrade urijs to version 1.19.4 to resolve security issue.
> chore (urijs) bump version

- package.json
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>
<OVERALL SUMMARY OF PULL REQUEST>
- Added Package Repository Information<INSERT DESCRIPTION OF CHANGES>
> feat(package): add repository information to package.json

- .github/workflows/build.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
- A few adjustments to build CI:
- Switch to `npm ci`
- Remove useless caching (since `npm ci` removes node modules)
- Updates to dependencies
> fix(CI) A few adjustment to build workflow, remove useless caching

- .github/workflows/build.yml
- .github/workflows/publish.yml
- packages/concerto-cli/test.cto
- packages/concerto-cli/test.json
- packages/concerto-cli/test1.cto
- packages/concerto-cli/test1.json
- packages/concerto-cli/test1err.json
- packages/concerto-cli/test2.cto
- Another minor update to align with Cicero
> fix(build) add npm build

- package-lock.json
- packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js
- packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js
Fixes the typescript generator so that it works with models that use super types.
```
concerto-cli % node index.js compile --model ./test/models/dom.cto --target Typescript
15:21:21 - INFO: Compiled to Typescript in './output/'.
```
Output:
```
import {AccordParty} from './org.accordproject.cicero.contract';
import {Concept,Asset} from './concerto';
// export namespace org.accordproject.cicero.dom{
export class Metadata extends Concept {
version: string;
locale: string;
}
export abstract class Element extends Asset {
id: string;
}
export class ContractTemplate extends Element {
metadata: Metadata;
content: Section;
}
export class ClauseTemplate extends Element {
metadata: Metadata;
content: Section;
}
export class Text extends Element { …
```
> fix(typescript) : imports for super types #320

- package-lock.json
- packages/concerto-core/lib/introspect/metamodel.js
- packages/concerto-core/test/data/model/empty.cto
- packages/concerto-core/test/data/model/empty.json
- packages/concerto-core/test/data/model/emptyResolved.json
- packages/concerto-core/test/introspect/metamodel.js
- Metamodel allows no declarations so name resolution should work when there is no enum or class declaration
> fix(core) metamodel with name resolution should work when no declaration is present

- packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js
- packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> fix(*): set typescript enum values to strings (resolves #362)

- packages/concerto-core/index.js
- packages/concerto-cto/index.js
- packages/concerto-util/index.js
- packages/concerto-vocabulary/index.js
- Updates the module JSDoc which shows up in the generated docs.
- <ONE>
- <TWO>
> docs: update the module descriptions

- package.json
- packages/concerto-cli/package.json
- packages/concerto-cto/package.json
- packages/concerto-metamodel/package.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package.json
- Update all `engines` descriptions in package.json files to require node 14
> chore(build): Update engines constraints in all package.json

- package-lock.json
- packages/concerto-core/api.txt
- packages/concerto-core/changelog.txt
- packages/concerto-core/lib/introspect/classdeclaration.js
- packages/concerto-core/test/introspect/classdeclaration.js
- packages/concerto-core/types/lib/introspect/classdeclaration.d.ts
- packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js
- packages/concerto-tools/test/codegen/fromcto/typescript/typescriptvisitor.js
This adds the ability to export a union type when a declaration has direct sub classes.
- Adds a `getDirectSubclasses` function to the Class Declaration class, to be able to find if a class declaration has sub classes
- During TS generation, checks if direct sub classes exists and if they do, then generates a union for them
N/A?
N/A?
- Issue #429
> feat(types): Adding support for union types to TS generation.

- packages/concerto-core/lib/datetimeutil.js
- packages/concerto-core/test/datetimeutil.js
Signed-off-by: Ayman161803 <mohammedaymannawaz@gmail.com>
- Improve error logs in datetimeutil.js as suggested [here](https://github.com/accordproject/cicero/issues/740)
- Replace the previous error log from test suite
- Issue accordproject/cicero#740
> fix(concerto-core): Improve error logs in datetimeutil.js

- packages/concerto-cli/index.js
- packages/concerto-cli/lib/commands.js
- packages/concerto-cli/package.json
- packages/concerto-cli/test/cli.js
- packages/concerto-cli/test/models/badversion.cto
- packages/concerto-cli/test/models/version.cto
- Add new `concerto version` command to manage version numbers in model files (both CTO and JSON metamodel)
- Supports automated release bumps - bump patch level, bump minor level, bump major level
- Supports explicit version specification - set version to x.y.z
- Supports globs to handle multiple files in a single argument
- Supports both CTO and JSON metamodel files
```
% concerto version 4.0.1 --model **/*.cto
17:22:27 - INFO: Updated version of "/Users/Simon.Stone/git/models-registry/features/fixtures/a.cto" from "3.4.5" to "4.0.1"
```
```
% concerto version patch --model **/*.cto
17:22:27 - INFO: Updated version of "/Users/Simon.Stone/git/models-registry/features/fixtures/a.cto" from "3.4.5" to "3.4.6"
```
```
% concerto version minor--model **/*.cto
17:22:27 - INFO: Updated version …
```
> feat(cli): add new concerto version command (contributes to #465)

- package-lock.json
- packages/concerto-core/.npmignore
- packages/concerto-core/package-lock.json
- packages/concerto-core/package.json
- packages/concerto-core/webpack.config.js
- packages/concerto-cto/package-lock.json
- packages/concerto-cto/package.json
- packages/concerto-cto/webpack.config.js
- packages/concerto-util/package.json
- packages/concerto-util/webpack.config.js
Modify the web pack configuration so that we can load concerto-core and concerto-cto in a React App created with `create-react-app`.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Webpack v5 Fixes

- package-lock.json
- packages/concerto-core/package-lock.json
- packages/concerto-util/package.json
Add `slash` to the dependencies for `concerto-util` which is used by `modelwriter.js`.
> fix(deps): add missing slash dependency

- packages/concerto-core/lib/basemodelmanager.js
- packages/concerto-core/lib/introspect/modelfile.js
- packages/concerto-core/lib/modelutil.js
- packages/concerto-core/messages/en.json
- packages/concerto-core/test/introspect/modelfile.js
- packages/concerto-core/types/lib/modelutil.d.ts
- packages/concerto-cto/lib/parser.js
- packages/concerto-cto/lib/parser.pegjs
- packages/concerto-util/package-lock.json
Enforce that multiple versions of the same namespace are not imported at the same time within the same file.
This also implicitly closes #461.
While testing I found a couple of bugs:
- Errors for `fileDownloader.downloadExternalDependencies` in the `baseModelManager` were not being caught.
- The CTO parser accepted incorrect fully-qualified versioned types such as `org.foo.Bar@2.0.0`. The correct form is `org.foo@2.0.0.Bar`.
> fix(core): fix wildcard import parsing, import hygiene

- packages/concerto-tools/lib/codegen/codegen.js
- packages/concerto-tools/lib/codegen/fromcto/markdown/markdownvisitor.js
- packages/concerto-tools/types/index.d.ts
- packages/concerto-tools/types/lib/codegen/codegen.d.ts
- packages/concerto-tools/types/lib/codegen/fromcto/markdown/markdownvisitor.d.ts
Converts the contents of a `ModelManager` to a markdown file, with a simple overview of each namespace and an inline Mermaid diagram for each namespace.
- Adds a `MarkdownVisitor` to concerto-tools
```
- 2 concepts
- 3 enumerations
- 2 assets
- 4 participants
- 1 transactions
- 2 events
- 14 total declarations
- concerto@1.0.0.Concept
- concerto@1.0.0.Asset
- concerto@1.0.0.Transaction
- concerto@1.0.0.Participant
- concerto@1.0.0.Event
```mermaid
classDiagram
class State {
<< enumeration>>
MA
NY
CO
WA
IL
CA
}
State --|> Concept
class Address {
<< concept>>
+String street
+String city
+State state
+String zipCode
+String country
}
Address --|> Concept
class Company {
<< concept>>
+String name
+Address headquarters
}
Company --|> Concept …
> feat(tools): add a markdown visitor

- packages/concerto-tools/lib/codegen/abstractplugin.js
- packages/concerto-tools/lib/codegen/fromcto/java/emptyplugin.js
- packages/concerto-tools/types/lib/codegen/abstractplugin.d.ts
- packages/concerto-tools/types/lib/codegen/fromcto/java/emptyplugin.d.ts
More fun with Typescript types, this time for `EmptyPlugin`.
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Typescript type definitions for EmptyPlugin

- packages/concerto-tools/lib/codegen/fromcto/openapi/openapivisitor.js
- Clean-up code by using [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing).
- <ONE>
- <TWO>
> chore(tools) : use nullish coalescing in openapi visitor

- packages/concerto-tools/lib/codegen/fromcto/markdown/markdownvisitor.js
- packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap
Signed-off-by: Diana Lease <dianarlease@gmail.com>
- <ONE> I'd like the mermaid code blocks that get generated when compiling to markdown to include relationships and hide the base model
- <TWO> After this is merged and released, I will update https://github.com/accordproject/vscode-web-extension/pull/10
- <ONE>
- <TWO>
> feat(markdownvisitor): add new params to mermaid codegen used in markdown visitor

- package-lock.json
- packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js
- packages/concerto-tools/test/codegen/__snapshots__/codegen.js.snap
- Escapes the source and target of relationships and aggregation links in the diagram, otherwise they will fail to render as they may contain a `@` symbol
- <ONE>
- <TWO>
> Fix for PlantUML relationships and aggregations

- packages/concerto-vocabulary/lib/vocabulary.js
- packages/concerto-vocabulary/lib/vocabularymanager.js
- packages/concerto-vocabulary/test/__snapshots__/vocabularymanager.js.snap
- packages/concerto-vocabulary/test/org.acme_en-gb.voc
- packages/concerto-vocabulary/test/org.acme_en.voc
- packages/concerto-vocabulary/test/vocabularymanager.js
- Tests had to be added for the new changes
- Issue #645 
- Pull Request #664
> feat(vocabulary): old breaking test fixed

- packages/concerto-core/lib/basemodelmanager.js
- packages/concerto-core/lib/introspect/modelfile.js
- packages/concerto-core/test/modelmanager.js
- packages/concerto-core/types/lib/introspect/modelfile.d.ts
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> Update Type Defs

- README.md
- Added the correct link in readme
- <ONE>
- <TWO>
- Issue #733 >
> fix(readme): Added correct link in readme

- package-lock.json
- packages/concerto-core/package.json
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-vocabulary/package.json
upgrade concerto-metamodel to v3.9.0
> chore(*): upgrade concerto-metamodel

- DEVELOPERS.md
- updated developer contribution doc, use npx to install dependencies using lerna due v7 breaking changes
- <ONE>
- <TWO>
> docs(developer): use npx to install lerna

- package-lock.json
- packages/concerto-core/src/introspect/classdeclaration.js
- packages/concerto-core/src/introspect/decorated.js
- packages/concerto-core/src/introspect/modelfile.js
- packages/concerto-core/src/introspect/stringvalidator.js
- packages/concerto-core/src/introspect/validator.js
- packages/concerto-core/src/messages/en.json
- packages/concerto-core/src/typenotfoundexception.js
- packages/concerto-core/test/introspect/classdeclaration.js
- packages/concerto-core/test/introspect/modelfile.js
- packages/concerto-cto/src/parser.js
- packages/concerto-cto/src/parser.pegjs
- packages/concerto-cto/src/printer.js
- packages/concerto-cto/test/cto/bad/self-extending-asset.bad.cto
- packages/concerto-cto/test/cto/bad/self-extending-concept.bad.cto
- packages/concerto-cto/test/cto/bad/self-extending-event.bad.cto
- packages/concerto-cto/test/cto/bad/self-extending-participant.bad.cto
- packages/concerto-cto/test/cto/bad/self-extending-transaction.bad.cto
- packages/concerto-cto/test/parserMain.js
- packages/concerto-cto/test/printer.js
- packages/concerto-util/src/baseexception.js
- packages/concerto-util/src/errorcodes.js
- packages/concerto-util/src/index.ts
- packages/concerto-util/types/index.d.ts
- packages/concerto-util/types/lib/baseexception.d.ts
- packages/concerto-util/types/lib/errorcodes.d.ts
> chore(*): port v3 fixes to v4

- packages/concerto-cto/src/parser.js
- packages/concerto-cto/src/parser.pegjs
- packages/concerto-cto/test/cto/semver-imports.cto
- packages/concerto-cto/test/cto/semver-imports.json
- Extends the parser to support additional patterns of namespaces that were previously resulted in parse errors:
```
// Cases where trailing Type is not a valid semver pre-release or build part
import b@1.0.0-a+b.पः
import b@1.0.0-a.a+b.पः
import b@1.0.0-a+b.c.पः
import b@1.0.0+b.पः
import b@1.0.0+b.c.पः
import b@1.0.0-a.पः
import b@1.0.0-a.a.पः
import b@1.0.0.पः
// Previously ambiguous cases where the trailing type is also a valid semver pre-release or build part
import b@1.0.0-a+b.A
import b@1.0.0-a.a+b.b.A
import b@1.0.0-a+b.b.A
import b@1.0.0-a.a+b.A
import b@1.0.0+b.A
import b@1.0.0+b.b.A
import b@1.0.0-a.A
import b@1.0.0-a.a.A
import b@1.0.0.A
import b@1.0.0+-a.A 
```
> fix(cto): allow imports with semver build and prerelease parts 

- package-lock.json
- packages/concerto-analysis/package-lock.json
- packages/concerto-core/package-lock.json
- packages/concerto-cto/package-lock.json
- packages/concerto-types/package-lock.json
- packages/concerto-util/package-lock.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package-lock.json
I'm not sure why this wasn't picked up by dependabot, but previous version had a dependency on a vulnerable version of follow-redirects
- Manually update axios
- <ONE>
- <TWO>
> chore(dep): update axios to safe ver

- package-lock.json
- packages/concerto-core/package.json
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-vocabulary/package.json
- Updates `concerto-metamodel` version.
- <ONE>
- <TWO>
> chore(deps): update concerto-metamodel version

- package-lock.json
- packages/concerto-core/changelog.txt
- packages/concerto-core/package.json
- packages/concerto-core/types/lib/basemodelmanager.d.ts
> fix(test): update the change log with correct hash

- packages/concerto-core/api.txt
- packages/concerto-core/changelog.txt
- packages/concerto-core/lib/introspect/modelfile.js
- packages/concerto-core/test/introspect/modelfile.js
- packages/concerto-core/types/lib/introspect/modelfile.d.ts
This API is useful for developing the concerto-codegen for the aliasing support
- Issue #889
> feat(aliasing): getImportedType() in model Flle in aliasing

- lerna.json
- package-lock.json
- package.json
- packages/concerto-analysis/package-lock.json
- packages/concerto-analysis/package.json
- packages/concerto-core/package-lock.json
- packages/concerto-core/package.json
- packages/concerto-cto/package-lock.json
- packages/concerto-cto/package.json
- packages/concerto-types/package-lock.json
- packages/concerto-types/package.json
- packages/concerto-util/package-lock.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package-lock.json
- packages/concerto-vocabulary/package.json
In order to manually trigger the PR I had merged on empty commit using another PR, but the DCO failed for the merge commit. While fixing that I lost original head of the commit tree due to a force push. Apologies for the mess.
So I manually ran the following commands to update npm package version that were triggered during the publish pipeline.
```
npm version --no-git-tag-version --yes --exact 3.19.1
npx lerna version --no-git-tag-version --yes --exact 3.19.1
```
- <ONE>
- <TWO>
- <ONE>
- <TWO>
> chore(actions): publish v3.19.1 to npm

- package-lock.json
- package.json
- packages/concerto-analysis/package.json
- packages/concerto-core/package.json
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package.json
- Bumps package version to 3.19.3
- <ONE>
- <TWO>
> chore(version): bump package version to 3.19.3

- package-lock.json
- packages/concerto-analysis/package.json
- packages/concerto-core/package.json
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-vocabulary/package.json
Update `concerto-codegen` and internal packages
> chore: update codegen and internal packages

- package-lock.json
- package.json
- packages/concerto-analysis/package.json
- packages/concerto-core/package.json
- packages/concerto-core/test/scripts/changelog.js
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package.json
- Remove vulnerable dependencies and bump version to match latest release
```
npm audit
found 0 vulnerabilities
```
> fix(*): remove vulnerable deps and bump version

- package-lock.json
- package.json
- packages/concerto-analysis/package.json
- packages/concerto-core/package.json
- packages/concerto-cto/package.json
- packages/concerto-types/package.json
- packages/concerto-util/package.json
- packages/concerto-vocabulary/package.json
> fix(package): update package

- packages/concerto-util/package.json
This is a fix for browser pointer in concerto-util pkg json. With this we should be able to build a stable package build for concerto packages in the browser.
> bug(util): fix browser pointer in concerto-util pkg json
